<a href="https://colab.research.google.com/github/Saputoa21/Introduction_Machine_Learning-Information_Retrieval/blob/main/Retrieval_System_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Retrieval System Project**: Agatha Christie's Books

## 1. Downloading Texts

In [ ]:
!git clone https://github.com/Saputoa21/Machine-Learning.git
!ls Machine-Learning

fatal: destination path 'Machine-Learning' already exists and is not an empty directory.
 01_LM_NLP_python_basics_Anastasiya_SAPUTO.ipynb
 02_Gender_Identification_with_Decision_Tree_Anastasiya_SAPUTO.ipynb
 03_Probabelistic_Modeling_Naive_Bayes_Anastasiya_SAPUTO.ipynb
 Agatha_Christie_Corpus.zip
 extracted_files
 Inverted_index_exercise.ipynb
'O4_LM_LDA_Topic_modelling_SAPUTO_2024 (1).ipynb'
 Retrieval_System_Project.ipynb

In [ ]:
import zipfile
import os

zip_path = "Machine-Learning/Agatha_Christie_Corpus.zip"
extract_path = "Machine-Learning/extracted_files"

# Create a directory to extract if it doesn't exist
os.makedirs(extract_path, exist_ok=True)

# Extract the ZIP file
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

# List extracted files
!ls Machine-Learning/extracted_files

'Poirot Investigates_pg61262.txt'
'The Big Four_pg70114.txt'
"The Hunter's Lodge Case_pg67160.txt"
'The man in the Brown Suit_pg61168.txt'
'The Missing Will_pg67173.txt'
'The Murder of Roger Ackroyd_pg69087.txt'
'The Murder on the Links_pg58866.txt'
'The Mysterious Affair at Styles_pg863.txt'
'The Mystery of the Blue Train_pg72824.txt'
'The Plymouth Express Affair_pg66446.txt'
'The Secret Adversary_pg1155.txt'
'The Secret of Chimneys_pg65238.txt'
'The Seven Dials Mystery_pg75288.txt'

In [ ]:
file_path = "Machine-Learning/extracted_files/Poirot Investigates_pg61262.txt"

with open(file_path, "r", encoding="utf-8") as file:
    content = file.read()
    print(content[:1000])

﻿The Project Gutenberg eBook of Poirot Investigates

This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.

Title: Poirot Investigates

Author: Agatha Christie

Release date: January 28, 2020 [eBook #61262]
                Most recently updated: October 17, 2024

Language: English

Credits: Produced by an anonymous Project Gutenberg volunteer.


*** START OF THE PROJECT GUTENBERG EBOOK POIROT INVESTIGATES ***

  POIROT INVESTIGATES




  BY THE SAME AUTHOR

  THE MYSTERIOUS AFFAIR AT STYLES

  THE SECRET ADVERSARY

  THE MURDER ON THE LINKS

  THE BODLEY HEAD




  POIROT INVESTIGATES

  BY AGATHA CH

## 2. Creating the Dataframe from Texts

In [ ]:
filenames = sorted(os.listdir(extract_path))

In [ ]:
import pandas as pd

texts = []
filenames_sorted = []
for filename in filenames:
    if filename.endswith(".txt"):
        division = filename.find("_")
        file_path = os.path.join(extract_path, filename[:])
        with open(file_path, "r", encoding="utf-8", errors="ignore") as file:
            filenames_sorted.append(filename)
            texts.append(file.read())

# Create a DataFrame
df = pd.DataFrame({"book_title": filenames, "content": texts})

df.insert(0, 'book_id', range(0, len(df)))

In [ ]:
print(df) #print the dataframe

    book_id                                 book_title  \
0         0      The man in the Brown Suit_pg61168.txt
1         1        The Hunter's Lodge Case_pg67160.txt
2         2            The Secret Adversary_pg1155.txt
3         3        The Seven Dials Mystery_pg75288.txt
4         4  The Mystery of the Blue Train_pg72824.txt
5         5            Poirot Investigates_pg61262.txt
6         6    The Murder of Roger Ackroyd_pg69087.txt
7         7                   The Big Four_pg70114.txt
8         8        The Murder on the Links_pg58866.txt
9         9  The Mysterious Affair at Styles_pg863.txt
10       10    The Plymouth Express Affair_pg66446.txt
11       11         The Secret of Chimneys_pg65238.txt
12       12               The Missing Will_pg67173.txt

                                              content
0   ﻿The Project Gutenberg eBook of The Man in the...
1   ﻿The Project Gutenberg eBook of The Hunter's L...
2   ﻿The Project Gutenberg eBook of The Secret Adv...
3   ﻿The Project Gutenberg eBook of The Seven Dial...
4   ﻿The Project Gutenberg eBook of The mystery of...
5   ﻿The Project Gutenberg eBook of Poirot Investi...
6   ﻿The Project Gutenberg eBook of The murder of ...
7   ﻿The Project Gutenberg eBook of The Big Four\n...
8   ﻿The Project Gutenberg eBook of The Murder on ...
9   ﻿The Project Gutenberg eBook of The Mysterious...
10  ﻿The Project Gutenberg eBook of The Plymouth E...
11  ﻿The Project Gutenberg eBook of The Secret of ...
12  ﻿The Project Gutenberg eBook of The Missing Wi...

In [ ]:
# Clean book title by removing the "_pgXXXXX.txt" part
df["book_title"] = df["book_title"].str.replace(r"_pg\d+\.txt$", "", regex=True)

In [ ]:
print(df)

    book_id                       book_title  \
0         0        The man in the Brown Suit
1         1          The Hunter's Lodge Case
2         2             The Secret Adversary
3         3          The Seven Dials Mystery
4         4    The Mystery of the Blue Train
5         5              Poirot Investigates
6         6      The Murder of Roger Ackroyd
7         7                     The Big Four
8         8          The Murder on the Links
9         9  The Mysterious Affair at Styles
10       10      The Plymouth Express Affair
11       11           The Secret of Chimneys
12       12                 The Missing Will

                                              content
0   ﻿The Project Gutenberg eBook of The Man in the...
1   ﻿The Project Gutenberg eBook of The Hunter's L...
2   ﻿The Project Gutenberg eBook of The Secret Adv...
3   ﻿The Project Gutenberg eBook of The Seven Dial...
4   ﻿The Project Gutenberg eBook of The mystery of...
5   ﻿The Project Gutenberg eBook of Poirot Investi...
6   ﻿The Project Gutenberg eBook of The murder of ...
7   ﻿The Project Gutenberg eBook of The Big Four\n...
8   ﻿The Project Gutenberg eBook of The Murder on ...
9   ﻿The Project Gutenberg eBook of The Mysterious...
10  ﻿The Project Gutenberg eBook of The Plymouth E...
11  ﻿The Project Gutenberg eBook of The Secret of ...
12  ﻿The Project Gutenberg eBook of The Missing Wi...

In [ ]:
print(df['content'][0][:3000]) #printing the first book content

﻿The Project Gutenberg eBook of The Man in the Brown Suit

This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.

Title: The Man in the Brown Suit

Author: Agatha Christie

Release date: January 14, 2020 [eBook #61168]
                Most recently updated: October 17, 2024

Language: English

Credits: an anonymous Project Gutenberg volunteer


*** START OF THE PROJECT GUTENBERG EBOOK THE MAN IN THE BROWN SUIT ***

  THE MAN IN THE BROWN SUIT




  BY THE SAME AUTHOR

  THE MYSTERIOUS AFFAIR AT STYLES

  THE SECRET ADVERSARY

  THE MURDER ON THE LINKS




  THE MAN IN THE BROWN SUIT
  by
  AGATHA CHRISTIE

  NEW YORK

  DODD, MEAD AND COMPANY

  1924





  Copyright, 1924,
  By DODD, MEAD AND COMPANY, Inc.

  PRINTED IN THE U. S. A. BY
  The Quinn & Boden Company
  BOOK MANUFACTURERS
  RAHWAY   NEW JERSEY




  To E. A. B.

  IN MEMORY OF A JOURNEY, SOME
  LION STORIES AND A REQUEST THAT
  I SHOULD SOME DAY WRITE THE
  “MYSTERY OF THE MILL HOUSE”



  THE MAN IN THE BROWN SUIT




  THE MAN IN THE BROWN SUIT


  PROLOGUE


Nadina, the Russian dancer who had taken Paris by storm, swayed to
the sound of the applause, bowed and bowed again. Her narrow black
eyes narrowed themselves still more, the long line of her scarlet
mouth curved faintly upwards. Enthusiastic Frenchmen continued to
beat the ground appreciatively as the curtain fell with a swish,
hiding the reds and blues and magentas of the bizarre _décors._ In
a swirl of blue and orange draperies the dancer left the stage. A
bearded gentleman received her enthusiastically in his arms. It
was the Manager.

“Magnificent, _petite,_ magnificent,” he cried. “To-night you have
surpassed yourself.” He kissed her gallantly on both cheeks in a
somewhat matter-of-fact manner.

Madame Nadina accepted the tribute with the ease of long habit and
passed on to her dressing-room, where bouquets were heaped
carelessly everywhere, marvellous garments of futuristic design
hung on pegs, and the air was hot and sweet with the scent of the
massed blossoms and with more sophisticated perfumes and essences.
Jeanne, the dresser, ministered to her mistress, talking incessantly
and pouring out a stream of fulsome compliment.

A knock at the door interrupted the flow. Jeanne went to answer
it, and returned with a card in her hand.

“Madame will receive?”

“Let me see.”

The dancer stretched out a languid hand, but at the sight of the
name on the card, “Count Sergius Paulovitch,” a sudden flicker of
interest came into her eyes.

“I will see him. The maize _peignoir,_ Jeanne, and quickly. And
when the Count comes you may go.”

_“Bien, M

Problem with paragraphing - possible if not removing empty lines first

In [ ]:
book_1 = df['content'][8] #I have chosen it as it has a clear contents section

In [ ]:
paragraphs = [p.strip() for p in book_1.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

df_par.tail()

                                              Paragraph
2708  Section 5. General Information About Project G...
2709  Professor Michael S. Hart was the originator o...
2710  Project Gutenberg™ eBooks are often created fr...
2711  Most people start at our website which has the...
2712  This website includes information about Projec...

## 3. Testing Cleaning and Splitting on One Book

In [ ]:
# Remove empty lines and join all lines into one
cleaned_book_1 = "\n".join([line.strip() for line in book_1.split("\n") if line.strip()])

print(cleaned_book_1[:2000])

﻿The Project Gutenberg eBook of The Murder on the Links
This ebook is for the use of anyone anywhere in the United States and
most other parts of the world at no cost and with almost no restrictions
whatsoever. You may copy it, give it away or re-use it under the terms
of the Project Gutenberg License included with this ebook or online
at www.gutenberg.org. If you are not located in the United States,
you will have to check the laws of the country where you are located
before using this eBook.
Title: The Murder on the Links
Author: Agatha Christie
Release date: February 11, 2019 [eBook #58866]
Most recently updated: November 30, 2022
Language: English
Credits: Alex Cabal
*** START OF THE PROJECT GUTENBERG EBOOK THE MURDER ON THE LINKS ***
cover
The Murder on the Links
by Agatha Christie
TO MY HUSBAND
A fellow enthusiast for detective stories, and to whom I am indebted for much
helpful advice and criticism.
Contents
1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
24 “Save Him!”
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End
1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the excl

In [ ]:
paragraphs = [p.strip() for p in cleaned_book_1.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

df_par.tail()

                                           Paragraph
0  ﻿The Project Gutenberg eBook of The Murder on ...

### Deleting Irrelevant Book Parts

In [ ]:
import re

# Splitting lines and deleting metadata of the Guteberg's project
lines = cleaned_book_1.split("\n")
start_idx = 0
end_idx = 0

for i, line in enumerate(lines):
  if "*** START OF THE PROJECT GUTENBERG EBOOK" in line:
    start_idx = i + 1
  if "*** END OF THE PROJECT GUTENBERG EBOOK" in line:
    end_idx = i
    break

In [ ]:
book_1_wo_metadata = "\n".join(lines[start_idx:end_idx])

print(book_1_wo_metadata[:1500])

lines = book_1_wo_metadata.split("\n")

cover
The Murder on the Links
by Agatha Christie
TO MY HUSBAND
A fellow enthusiast for detective stories, and to whom I am indebted for much
helpful advice and criticism.
Contents
1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
24 “Save Him!”
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End
1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the exclamation was not a Duchess!
It was a day in early June. I had been transacting some business in
Paris and was returning by the morning service to London where I was
still sharing rooms with my old friend, the Belgian ex-detective,
Hercule Poirot.
The

In [ ]:
lines[:10]

['cover',
 'The Murder on the Links',
 'by Agatha Christie',
 'TO MY HUSBAND',
 'A fellow enthusiast for detective stories, and to whom I am indebted for much',
 'helpful advice and criticism.',
 'Contents',
 '1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève']

In [ ]:
print(len(lines))

6506

Problem with paragraphing texts - no more possible due to removing /n fisrt

In [ ]:
paragraphs = [p.strip() for p in book_1_wo_metadata.split('\n\n') if p.strip()]

# Create DataFrame
df_par = pd.DataFrame(paragraphs, columns=["Paragraph"])

In [ ]:
df_par.tail()

                                           Paragraph
0  cover\nThe Murder on the Links\nby Agatha Chri...

### Finding chapters

In [ ]:
import re

# Extracting chapters

"""
# As some books are formatted differently, I need to have several options for identification the chapters, e.g:
PROLOGUE
CHAPTER I. I GO TO STYLES
I  DR. SHEPPARD AT THE BREAKFAST TABLE
I The Adventure of “The Western Star”
CHAPTER I.   THE YOUNG ADVENTURERS, LTD.
1 A Fellow Traveller
XVIII JIMMY'S ADVENTURES
1. The Man with the White Hair
CHAPTER I
11. A CHESS PROBLEM
1 ANTHONY CADE SIGNS ON
*       *       *       *       *

"""

chapter_regex = re.compile(
    r"^("
    r"PROLOGUE$|"
    r"CHAPTER\s+[IVXLCDM]+\.\s+[^\n]+|"    # CHAPTER I. Title
    r"CHAPTER\s+[IVXLCDM]+$|"              # CHAPTER I
    r"[IVXLCDM]{1,4}\s{1,}[A-Z][^\n]+|"    # I Title
    r"\d+\.\s+[A-Z][^\n]+|"                # 1. Title
    r"\d+\s+[A-Z][^\n]+|"                  # 1 Title
    r"\*+(\s+\*+)+$"                       # * * * * *
    r")$",
    re.MULTILINE
)

In [ ]:
#finding chapters with the regex object
matches = re.findall(chapter_regex, book_1_wo_metadata)

print(matches)

[('1 A Fellow Traveller', ''), ('2 An Appeal for Help', ''), ('3 At the Villa Geneviève', ''), ('4 The Letter Signed “Bella”', ''), ('5 Mrs. Renauld’s Story', ''), ('6 The Scene of the Crime', ''), ('7 The Mysterious Madame Daubreuil', ''), ('8 An Unexpected Meeting', ''), ('9 M. Giraud Finds Some Clues', ''), ('10 Gabriel Stonor', ''), ('11 Jack Renauld', ''), ('12 Poirot Elucidates Certain Points', ''), ('13 The Girl with the Anxious Eyes', ''), ('14 The Second Body', ''), ('15 A Photograph', ''), ('16 The Beroldy Case', ''), ('17 We Make Further Investigations', ''), ('18 Giraud Acts', ''), ('19 I Use My Grey Cells', ''), ('20 An Amazing Statement', ''), ('21 Hercule Poirot on the Case!', ''), ('22 I Find Love', ''), ('23 Difficulties Ahead', ''), ('25 An Unexpected Dénouement', ''), ('26 I Receive a Letter', ''), ('27 Jack Renauld’s Story', ''), ('28 Journey’s End', ''), ('1 A Fellow Traveller', ''), ('2 An Appeal for Help', ''), ('3 At the Villa Geneviève', ''), ('4 The Letter Signed “Bella”', ''), ('5 Mrs. Renauld’s Story', ''), ('6 The Scene of the Crime', ''), ('7 The Mysterious Madame Daubreuil', ''), ('8 An Unexpected Meeting', ''), ('9 M. Giraud Finds Some Clues', ''), ('10 Gabriel Stonor', ''), ('11 Jack Renauld', ''), ('12 Poirot Elucidates Certain Points', ''), ('13 The Girl with the Anxious Eyes', ''), ('14 The Second Body', ''), ('15 A Photograph', ''), ('16 The Beroldy Case', ''), ('17 We Make Further Investigations', ''), ('18 Giraud Acts', ''), ('19 I Use My Grey Cells', ''), ('20 An Amazing Statement', ''), ('21 Hercule Poirot on the Case!', ''), ('22 I Find Love', ''), ('23 Difficulties Ahead', ''), ('25 An Unexpected Dénouement', ''), ('26 I Receive a Letter', ''), ('27 Jack Renauld’s Story', ''), ('28 Journey’s End', '')]

In [ ]:
#there are sometimes lines breaks or white spaces which should be avoided (in some books)
def contains_newline(text):
    return '\n' in text

chapters = [m[0] for m in matches if not contains_newline(m[0])] # The outputs are tuples so we need the 1 part from them

In [ ]:
#removing duplicates as usually chapter names come twice (in the table of contens and in the beginning of each chpater)
seen = []
chapter_list = []
for chapter in chapters:
    if chapter not in seen:
        seen.append(chapter)
        chapter_list.append(chapter)

# I did not used the option with a set as the order of chapters gets lost, while the reordering it back with transforming into a list and applying sort method does work right.

In [ ]:
print(chapter_list)
print(type(chapter_list))
print(len(chapter_list))

['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End']
<class 'list'>
27

In [ ]:
#printing out chapters
for m in chapter_list:
    print(m)

1 A Fellow Traveller
2 An Appeal for Help
3 At the Villa Geneviève
4 The Letter Signed “Bella”
5 Mrs. Renauld’s Story
6 The Scene of the Crime
7 The Mysterious Madame Daubreuil
8 An Unexpected Meeting
9 M. Giraud Finds Some Clues
10 Gabriel Stonor
11 Jack Renauld
12 Poirot Elucidates Certain Points
13 The Girl with the Anxious Eyes
14 The Second Body
15 A Photograph
16 The Beroldy Case
17 We Make Further Investigations
18 Giraud Acts
19 I Use My Grey Cells
20 An Amazing Statement
21 Hercule Poirot on the Case!
22 I Find Love
23 Difficulties Ahead
25 An Unexpected Dénouement
26 I Receive a Letter
27 Jack Renauld’s Story
28 Journey’s End

### Finding the main content of the book

In [ ]:
lines[:10]

['cover',
 'The Murder on the Links',
 'by Agatha Christie',
 'TO MY HUSBAND',
 'A fellow enthusiast for detective stories, and to whom I am indebted for much',
 'helpful advice and criticism.',
 'Contents',
 '1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève']

In [ ]:
#finding the Contents section
def find_main_book_content(lines, chapter_list):
    found_contents = False
    contents_start_idx = 0
    contents_end_idx = 0
    book_end = len(lines)
    for i, line in enumerate(lines):
        if "Contents" in line or "CONTENTS" in line:
            contents_start_idx = i + 1
            found_contents = True
        if line.strip() == chapter_list[-1]:  #last chapter in the list and contents table
            contents_end_idx = i
            book_start = contents_end_idx + 1
            break

    if not found_contents:  #if no "Contents" section found (true for some books)
        for i, line in enumerate(lines):
            if line.strip() in chapter_list:
                contents_start_idx = i
                book_start = contents_start_idx +1
                break
    return slice(book_start, book_end) #creating out of a tuple with indeces a slice for a list

In [ ]:
#extracting and joining the main book content
book_1_main_lines = lines[find_main_book_content(lines, chapter_list)]
book_1_main_content = "\n".join(book_1_main_lines)

In [ ]:
print(book_1_main_content[:1000])

1 A Fellow Traveller
I believe that a well-known anecdote exists to the effect that a young
writer, determined to make the commencement of his story forcible and
original enough to catch and rivet the attention of the most blasé of
editors, penned the following sentence:
“‘Hell!’ said the Duchess.”
Strangely enough, this tale of mine opens in much the same fashion.
Only the lady who gave utterance to the exclamation was not a Duchess!
It was a day in early June. I had been transacting some business in
Paris and was returning by the morning service to London where I was
still sharing rooms with my old friend, the Belgian ex-detective,
Hercule Poirot.
The Calais express was singularly empty—in fact, my own compartment
held only one other traveller. I had made a somewhat hurried departure
from the hotel and was busy assuring myself that I had duly collected
all my traps when the train started. Up till then I had hardly noticed
my companion, but I was now violently recalled to the fact of

### Splitting the book into chapters and paragraphs

In [ ]:
chapter_list

['1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève',
 '4 The Letter Signed “Bella”',
 '5 Mrs. Renauld’s Story',
 '6 The Scene of the Crime',
 '7 The Mysterious Madame Daubreuil',
 '8 An Unexpected Meeting',
 '9 M. Giraud Finds Some Clues',
 '10 Gabriel Stonor',
 '11 Jack Renauld',
 '12 Poirot Elucidates Certain Points',
 '13 The Girl with the Anxious Eyes',
 '14 The Second Body',
 '15 A Photograph',
 '16 The Beroldy Case',
 '17 We Make Further Investigations',
 '18 Giraud Acts',
 '19 I Use My Grey Cells',
 '20 An Amazing Statement',
 '21 Hercule Poirot on the Case!',
 '22 I Find Love',
 '23 Difficulties Ahead',
 '25 An Unexpected Dénouement',
 '26 I Receive a Letter',
 '27 Jack Renauld’s Story',
 '28 Journey’s End',
 '1 A Fellow Traveller',
 '2 An Appeal for Help',
 '3 At the Villa Geneviève',
 '4 The Letter Signed “Bella”',
 '5 Mrs. Renauld’s Story',
 '6 The Scene of the Crime',
 '7 The Mysterious Madame Daubreuil',
 '8 An Unexpected Meeting',
 '9 M. Giraud Finds Some Clues',
 '10 Gabriel Stonor',
 '11 Jack Renauld',
 '12 Poirot Elucidates Certain Points',
 '13 The Girl with the Anxious Eyes',
 '14 The Second Body',
 '15 A Photograph',
 '16 The Beroldy Case',
 '17 We Make Further Investigations',
 '18 Giraud Acts',
 '19 I Use My Grey Cells',
 '20 An Amazing Statement',
 '21 Hercule Poirot on the Case!',
 '22 I Find Love',
 '23 Difficulties Ahead',
 '25 An Unexpected Dénouement',
 '26 I Receive a Letter',
 '27 Jack Renauld’s Story',
 '28 Journey’s End']

In [ ]:
import pandas as pd

def extract_chapters_and_paragraphs(text, chapters_list, book_id=1, book_title="Unknown Title", paragraph_num = 5):
    lines = text.split("\n")

    # Step 1: Find indexes of each chapter title in the lines
    chapter_indices = []
    for i, line in enumerate(lines):
        if line in chapters_list:
            chapter_indices.append((line, i))

    # Step 2: Build chapter blocks
    chapters = []
    for idx, (chapter_title, start_idx) in enumerate(chapter_indices):
        end_idx = chapter_indices[idx + 1][1] if idx + 1 < len(chapter_indices) else len(lines)
        chapter_lines = lines[start_idx + 1:end_idx]
        chapter_text = "\n".join(chapter_lines).strip()

        chapters.append({
            "chapter_title": chapter_title,
            "chapter_text": chapter_text
        })

    final_rows = []

    for chap_id, chap in enumerate(chapters, 1):
      # Remove newlines and split text into words
      words = chap["chapter_text"].replace('\n', ' ').split()
      total_words = len(words)

      # Compute base chunk size
      chunk_size = total_words // paragraph_num
      remainder = total_words % paragraph_num

      start = 0
      for para_id in range(1, paragraph_num + 1):
        # Distribute the remainder across first few paragraphs
        end = start + chunk_size + (1 if para_id <= remainder else 0)
        para_words = words[start:end]
        paragraph_text = " ".join(para_words)

        final_rows.append({
            "book_id": book_id,
            "book_title": book_title,
            "chapter_id": chap_id,
            "chapter_title": chap["chapter_title"],
            "paragraph_id": para_id,
            "paragraph_text": paragraph_text
        })

        start = end

    return pd.DataFrame(final_rows)

In [ ]:
book_text = book_1_main_content
book_title = df.loc[8,"book_title"]
book_id = df.loc[8,"book_id"]
chapter_list = chapters
paragraph_num = 5

book_1_splitted_df = extract_chapters_and_paragraphs(book_text, chapter_list, book_id, book_title, paragraph_num)

In [ ]:
book_1_splitted_df

,book_id,book_title,chapter_id,chapter_title,paragraph_id,paragraph_text
0,8,The Murder on the Links,1,1 A Fellow Traveller,1,I believe that a well-known anecdote exists to...
1,8,The Murder on the Links,1,1 A Fellow Traveller,2,I’ve lost my only sister?” “Really?” I said po...
2,8,The Murder on the Links,1,1 A Fellow Traveller,3,mad?” I inquired with a smile. “A regular litt...
3,8,The Murder on the Links,1,1 A Fellow Traveller,4,"nodded. “You were through it, I suppose?” “Pre..."
4,8,The Murder on the Links,1,1 A Fellow Traveller,5,"operations, and stared at me with undisguised ..."
...,...,...,...,...,...,...
130,8,The Murder on the Links,27,28 Journey’s End,1,I have confused memories of the further events...
131,8,The Murder on the Links,27,28 Journey’s End,2,facts fail to support any theory of her guilt....
132,8,The Murder on the Links,27,28 Journey’s End,3,be wandering about carrying a souvenir paper-k...
133,8,The Murder on the Links,27,28 Journey’s End,4,"did I tell you? The shock of joy, it was too m..."
134,8,The Murder on the Links,27,28 Journey’s End,5,had been in actual fact a fugitive from justic...

## Cleaning and Splitting All Books to Create a Common Dataframe

In [ ]:
#modified functions that I have created based on 1 book testing

def delete_metadata(book):
  cleaned_book = "\n".join([line.strip() for line in book.split("\n") if line.strip()])
  lines = cleaned_book.split("\n")
  start_idx = 0
  end_idx = 0
  for i, line in enumerate(lines):
    if "*** START OF THE PROJECT GUTENBERG EBOOK" in line:
      start_idx = i + 1
    if "*** END OF THE PROJECT GUTENBERG EBOOK" in line:
      end_idx = i
      break
  book_wo_metadata = "\n".join(lines[start_idx:end_idx])
  return book_wo_metadata

def contains_newline(text):
    return '\n' in text

def find_chapters(book_wo_metadata, chapter_regex):
  seen = []
  chapter_list = []
  matches = re.findall(chapter_regex, book_wo_metadata)
  matches = [m[0] for m in matches if not contains_newline(m[0])]
  for chapter in matches:
    if chapter not in seen:
        seen.append(chapter)
        chapter_list.append(chapter)
  return chapter_list

def find_main_book_content(book_wo_metadata, chapter_list):
    lines = book_wo_metadata.split("\n")
    found_contents = False
    contents_start_idx = 0
    contents_end_idx = 0
    book_end = len(lines)
    for i, line in enumerate(lines):
        if "Contents" in line or "CONTENTS" in line:
            contents_start_idx = i + 1
            found_contents = True
        if line.strip() == chapter_list[-1]:  #last chapter in the list and conen table
            contents_end_idx = i
            book_start = contents_end_idx + 1
            break
    if not found_contents:  #if no "Contents" section found (true for some books)
        for i, line in enumerate(lines):
            if line.strip() in chapter_list:
                contents_start_idx = i
                book_start = contents_start_idx +1
                break
    main_content_slice = slice(book_start, book_end) #creating out of a tuple with indeces a slice for a list
    book_main_lines = lines[main_content_slice]
    book_main_content = "\n".join(book_main_lines)
    return book_main_content

In [ ]:
final_df = pd.DataFrame()

chapter_regex = re.compile(
    r"^("
    r"PROLOGUE$|"
    r"CHAPTER\s+[IVXLCDM]+\.\s+[^\n]+|"    # CHAPTER I. Title
    r"CHAPTER\s+[IVXLCDM]+$|"              # CHAPTER I
    r"[IVXLCDM]{1,4}\s{1,}[A-Z][^\n]+|"    # I Title
    r"\d+\.\s+[A-Z][^\n]+|"                # 1. Title
    r"\d+\s+[A-Z][^\n]+|"                  # 1 Title
    r"\*+(\s+\*+)+$"                       # * * * * *
    r")$",
    re.MULTILINE
)

for i in range(len(df)):
    try:
        #get book data from DataFrame row
        book_text = df.iloc[i]["content"]
        book_title = df.iloc[i]["book_title"]
        book_id = int(df.iloc[i]["book_id"]) #otherwise it looks like np.int64(4)

        #removing metadata
        book_wo_metadata = delete_metadata(book_text)

        #generating a unique chapter list for each book
        chapter_list = find_chapters(book_wo_metadata, chapter_regex)

        #finding the main content for each book (excluding the table of contents)
        book_main_content = find_main_book_content(book_wo_metadata, chapter_list)

        #checking whether all functions worked in the right way
        print(f"Chapter list for {book_title} (ID {book_id}): text '{book_main_content[:10]}', chapters: {chapter_list}, total: {len(chapter_list)})")

        #splitting into chapters and paragraphs
        paragraph_num = 7
        book_df = extract_chapters_and_paragraphs(book_main_content, chapter_list, book_id, book_title, paragraph_num)

        final_df = pd.concat([final_df, book_df], ignore_index=True)

    except Exception as e:
        print(f"[ERROR] Book ID {df.iloc[i]['book_id']} - {df.iloc[i]['book_title']}: {e}")

Chapter list for The man in the Brown Suit (ID 0): text '“MYSTERY O', chapters: ['I SHOULD SOME DAY WRITE THE', 'PROLOGUE', 'CHAPTER I', 'CHAPTER II', 'CHAPTER III', 'CHAPTER IV', 'CHAPTER V', 'CHAPTER VI', 'CHAPTER VII', 'CHAPTER VIII', 'CHAPTER IX', '17. How the number persisted. It was on the 17th I had sailed from', 'CHAPTER X', 'CHAPTER XI', 'CHAPTER XII', 'CHAPTER XIII', 'CHAPTER XIV', 'CHAPTER XV', 'CHAPTER XVI', 'CHAPTER XVII', 'CHAPTER XVIII', 'CHAPTER XIX', 'CHAPTER XX', 'CHAPTER XXI', 'CHAPTER XXII', 'CHAPTER XXIII', 'CHAPTER XXIV', 'CHAPTER XXV', 'CHAPTER XXVI', 'CHAPTER XXVII', 'CHAPTER XXVIII', 'CHAPTER XXIX', 'CHAPTER XXX', 'CHAPTER XXXI', 'CHAPTER XXXII', 'CHAPTER XXXIII', 'CHAPTER XXXIV', 'CHAPTER XXXV', 'CHAPTER XXXVI'], total: 39)
Chapter list for The Hunter's Lodge Case (ID 1): text 'To this I ', chapters: ['*       *       *       *       *'], total: 1)
Chapter list for The Secret Adversary (ID 2): text '“THAT was ', chapters: ['PROLOGUE', 'CHAPTER I. \xa0\xa0THE YOUNG ADVENTURERS, LTD.', 'CHAPTER II. \xa0\xa0MR. WHITTINGTON’S OFFER', 'CHAPTER III. \xa0\xa0A SET BACK', 'CHAPTER IV. \xa0\xa0WHO IS JANE FINN?', 'CHAPTER V. \xa0\xa0MR. JULIUS P. HERSHEIMMER', 'CHAPTER VI. \xa0\xa0A PLAN OF CAMPAIGN', 'CHAPTER VII. \xa0\xa0THE HOUSE IN SOHO', 'CHAPTER VIII. \xa0\xa0THE ADVENTURES OF TOMMY', 'CHAPTER IX. \xa0\xa0TUPPENCE ENTERS DOMESTIC SERVICE', 'CHAPTER X. \xa0\xa0ENTER SIR JAMES PEEL EDGERTON', 'CHAPTER XI. \xa0\xa0JULIUS TELLS A STORY', 'CHAPTER XII. \xa0\xa0A FRIEND IN NEED', 'CHAPTER XIII. \xa0\xa0THE VIGIL', 'CHAPTER XIV. \xa0\xa0A CONSULTATION', 'CHAPTER XV. \xa0\xa0TUPPENCE RECEIVES A PROPOSAL', 'CHAPTER XVI. \xa0\xa0FURTHER ADVENTURES OF TOMMY', 'CHAPTER XVII. \xa0\xa0ANNETTE', 'CHAPTER XVIII. \xa0\xa0THE TELEGRAM', 'CHAPTER XIX. \xa0\xa0JANE FINN', 'CHAPTER XX. \xa0\xa0TOO LATE', 'CHAPTER XXI. \xa0\xa0TOMMY MAKES A DISCOVERY', 'CHAPTER XXII. \xa0\xa0IN DOWNING STREET', 'CHAPTER XXIII. \xa0\xa0A RACE AGAINST TIME', 'CHAPTER XXIV. \xa0\xa0JULIUS TAKES A HAND', 'CHAPTER XXV. \xa0\xa0JANE’S STORY', 'CHAPTER XXVI. \xa0\xa0MR. BROWN', 'CHAPTER XXVII. \xa0\xa0A SUPPER PARTY AT THE _SAVOY_', 'CHAPTER XXVIII. \xa0\xa0\xa0\xa0AND AFTER', 'CHAPTER I. THE YOUNG ADVENTURERS, LTD.', 'CHAPTER II. MR. WHITTINGTON’S OFFER', 'CHAPTER III. A SET BACK', 'CHAPTER IV. WHO IS JANE FINN?', 'CHAPTER V. MR. JULIUS P. HERSHEIMMER', 'CHAPTER VI. A PLAN OF CAMPAIGN', 'CHAPTER VII. THE HOUSE IN SOHO', 'CHAPTER VIII. THE ADVENTURES OF TOMMY', 'CHAPTER IX. TUPPENCE ENTERS DOMESTIC SERVICE', 'CHAPTER X. ENTER SIR JAMES PEEL EDGERTON', 'CHAPTER XI. JULIUS TELLS A STORY', 'CHAPTER XII. A FRIEND IN NEED', 'CHAPTER XIII. THE VIGIL', 'CHAPTER XIV. A CONSULTATION', 'CHAPTER XV. TUPPENCE RECEIVES A PROPOSAL', 'CHAPTER XVI. FURTHER ADVENTURES OF TOMMY', 'CHAPTER XVII. ANNETTE', 'CHAPTER XVIII. THE TELEGRAM', 'CHAPTER XIX. JANE FINN', 'CHAPTER XX. TOO LATE', 'CHAPTER XXI. TOMMY MAKES A DISCOVERY', 'CHAPTER XXII. IN DOWNING STREET', 'CHAPTER XXIII. A RACE AGAINST TIME', 'CHAPTER XXIV. JULIUS TAKES A HAND', 'CHAPTER XXV. JANE’S STORY', 'CHAPTER XXVI. MR. BROWN', 'CHAPTER XXVII. A SUPPER PARTY AT THE _SAVOY_', 'CHAPTER XXVIII. AND AFTER'], total: 57)
Chapter list for The Seven Dials Mystery (ID 3): text 'LORD CATER', chapters: ['I ON EARLY RISING', 'II CONCERNING ALARUM CLOCKS', 'III THE JOKE THAT FAILED', 'IV A LETTER', 'V THE MAN IN THE ROAD', 'VI SEVEN DIALS AGAIN', 'VII BUNDLE PAYS A CALL', 'VIII VISITORS FOR JIMMY', 'IX PLANS', 'X BUNDLE VISITS SCOTLAND YARD', 'XI DINNER WITH BILL', 'XII INQUIRIES AT CHIMNEYS', 'XIII THE SEVEN DIALS CLUB', 'XIV THE MEETING OF THE SEVEN DIALS', 'XV THE INQUEST', 'XVI THE HOUSE PARTY AT THE ABBEY', 'XVII AFTER DINNER', "XIX BUNDLE'S ADVENTURES", "XX LORAINE'S ADVENTURES", 'XXI THE RECOVERY OF THE FORMULA', "XXII THE COUNTESS RADZKY'S STORY", 'XXIV BUNDLE WONDERS', 'XXV JIMMY LAYS HIS PLANS', 'XXVI MAINLY ABOUT GOLF', 'XXIX SINGULAR BEHAVIOUR OF GEORGE LOMAX', 'XXX AN URGENT SUMMONS', 'XXXI THE SEVEN DIALS', 'CHAPTER I', 'CHAPTER II', 'CHAPTER III', 'CHAPTER IV', 'CHAPTER V', 'CHAPTER VI', 'CHAPTER VII', 'CHAPTER VIII', 'CHAPTER IX', 'CHAPTER X', 'CHAPTER XI', 'CHAPTER XII', 'CHAPTER XIII', 'CHAPTER XIV', 'CHAPTER XV', 'CHAPTER XVI', 'CHAPTER XVII', 'CHAPTER XVIII', 'CHAPTER XIX', 'CHAPTER XX', 'CHAPTER XXI', 'CHAPTER XXII', 'CHAPTER XXIII', 'CHAPTER XXIV', 'CHAPTER XXV', 'CHAPTER XXVI', 'CHAPTER XXVII', 'CHAPTER XXVIII', 'CHAPTER XXIX', 'CHAPTER XXX', '14 Hunstanton Street with only one idea in his head--never to return.', 'CHAPTER XXXI', 'CHAPTER XXXII', 'CHAPTER XXXIII', 'CHAPTER XXXIV'], total: 62)
Chapter list for The Mystery of the Blue Train (ID 4): text 'Cast of Ch', chapters: ['1. The Man with the White Hair', '2. M. le Marquis', '3. Heart of Fire', '4. In Curzon Street', '5. A Useful Gentleman', '6. Mirelle', '7. Letters', '8. Lady Tamplin Writes a Letter', '9. An Offer Refused', '10. On the Blue Train', '11. Murder', '12. At the Villa Marguerite', '13. Van Aldin Gets a Telegram', "14. Ada Mason's Story", '15. The Comte de la Roche', '16. Poirot Discusses the Case', '17. An Aristocratic Gentleman', '18. Derek Lunches', '19. An Unexpected Visitor', '20. Katherine Makes a Friend', '21. At the Tennis', '22. M. Papopolous Breakfasts', '23. A New Theory', '24. Poirot Gives Advice', '25. Defiance', '26. A Warning', '27. Interview with Mirelle', '28. Poirot Plays the Squirrel', '29. A Letter From Home', '30. Miss Viner Gives Judgment', '31. Mr. Aarons Lunches', '32. Katherine and Poirot Compare Notes', '33. A New Theory', '34. The Blue Train Again', '35. Explanations', '36. By the Sea'], total: 36)
Chapter list for Poirot Investigates (ID 5): text 'POIROT INV', chapters: ['I The Adventure of “The Western Star”', 'II The Tragedy at Marsdon Manor', 'III The Adventure of the Cheap Flat', 'IV The Mystery of Hunter’s Lodge', 'V The Million Dollar Bond Robbery', 'VI The Adventure of the Egyptian Tomb', 'VII Jewel Robbery at the _Grand Metropolitan_', 'VIII The Kidnapped Prime Minister', 'IX The Disappearance of Mr. Davenheim', 'X The Adventure of the Italian Nobleman', 'XI The Case of the Missing Will'], total: 11)
Chapter list for The Murder of Roger Ackroyd (ID 6): text 'APOLOGIA
F', chapters: ['I  DR. SHEPPARD AT THE BREAKFAST TABLE                           1', 'II  WHO’S WHO IN KING’S ABBOT                                     7', 'III  THE MAN WHO GREW VEGETABLE MARROWS                           17', 'IV  DINNER AT FERNLY                                             31', 'V  MURDER                                                       49', 'VI  THE TUNISIAN DAGGER                                          65', 'VII  I LEARN MY NEIGHBOR’S PROFESSION                             75', 'VIII  INSPECTOR RAGLAN IS CONFIDENT                                92', 'IX  THE GOLDFISH POND                                           106', 'X  THE PARLORMAID                                              118', 'XI  POIROT PAYS A CALL                                          136', 'XII  ROUND THE TABLE                                             145', 'XIII  THE GOOSE QUILL                                             156', 'XIV  MRS. ACKROYD                                                165', 'XV  GEOFFREY RAYMOND                                            178', 'XVI  AN EVENING AT MAH JONG                                      190', 'XVII  PARKER                                                      202', 'XIX  FLORA ACKROYD                                               226', 'XX  MISS RUSSELL                                                238', 'XXI  THE PARAGRAPH IN THE PAPER                                  251', 'XXII  URSULA’S STORY                                              260', 'XXIV  RALPH PATON’S STORY                                         284', 'XXV  THE WHOLE TRUTH                                             289', 'XXVI  AND NOTHING BUT THE TRUTH                                   298', 'CHAPTER I', 'CHAPTER II', 'CHAPTER III', 'CHAPTER IV', 'CHAPTER V', 'CHAPTER VI', 'CHAPTER VII', 'I LEARN MY NEIGHBOR’S PROFESSION', 'CHAPTER VIII', 'CHAPTER IX', 'CHAPTER X', 'CHAPTER XI', 'CHAPTER XII', 'CHAPTER XIII', 'CHAPTER XIV', 'CHAPTER XV', 'CHAPTER XVI', '1. That of Colonel Carter: that Ralph was secretly married to Flora.', '2. That of Miss Ganett: that Roger Ackroyd had been secretly married to', '3. That of my sister: that Roger Ackroyd had married his housekeeper,', 'CHAPTER XVII', 'CHAPTER XVIII', 'CHAPTER XIX', 'CHAPTER XX', 'CHAPTER XXI', 'CHAPTER XXII', 'CHAPTER XXIII', 'CHAPTER XXIV', 'CHAPTER XXV', 'CHAPTER XXVI', '*       *       *       *       *', 'CHAPTER XXVII'], total: 56)
Chapter list for The Big Four (ID 7): text 'Poirot's f', chapters: ['750 Third Avenue', '1. THE UNEXPECTED GUEST', '2. THE MAN FROM THE ASYLUM', '3. WE HEAR MORE ABOUT LI CHANG YEN', '4. THE IMPORTANCE OF A LEG OF MUTTON', '5. DISAPPEARANCE OF A SCIENTIST', '6. THE WOMAN ON THE STAIRS', '7. THE RADIUM THIEVES', '8. IN THE HOUSE OF THE ENEMY', '9. THE YELLOW JASMINE MYSTERY', '10. WE INVESTIGATE AT CROFTLANDS', '11. A CHESS PROBLEM', '12. THE BAITED TRAP', '13. THE MOUSE WALKS IN', '14. THE PEROXIDE BLONDE', '15. THE TERRIBLE CATASTROPHE', '16. THE DYING CHINAMAN', '17. NUMBER FOUR WINS A TRICK', '18. IN THE FELSENLABYRYNTH', '*       *       *       *       *'], total: 20)
Chapter list for The Murder on the Links (ID 8): text '1 A Fellow', chapters: ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End'], total: 27)
Chapter list for The Mysterious Affair at Styles (ID 9): text 'CHAPTER I.', chapters: ['CHAPTER I. I GO TO STYLES', 'CHAPTER II. THE 16TH AND 17TH OF JULY', 'CHAPTER III. THE NIGHT OF THE TRAGEDY', 'CHAPTER IV. POIROT INVESTIGATES', 'CHAPTER V. “IT ISN’T STRYCHNINE, IS IT?”', 'CHAPTER VI. THE INQUEST', 'CHAPTER VII. POIROT PAYS HIS DEBTS', 'CHAPTER VIII. FRESH SUSPICIONS', 'CHAPTER IX. DR. BAUERSTEIN', 'CHAPTER X. THE ARREST', 'CHAPTER XI. THE CASE FOR THE PROSECUTION', 'CHAPTER XII. THE LAST LINK', 'CHAPTER XIII. POIROT EXPLAINS'], total: 13)
Chapter list for The Plymouth Express Affair (ID 10): text '“Mon ami,”', chapters: ['*       *       *       *       *'], total: 1)
Chapter list for The Secret of Chimneys (ID 11): text 'It was abo', chapters: ['1 ANTHONY CADE SIGNS ON      _1_', '2 A LADY IN DISTRESS      _11_', '3 ANXIETY IN HIGH PLACES      _20_', '4 INTRODUCING A VERY CHARMING LADY      _27_', '5 FIRST NIGHT IN LONDON      _33_', '6 THE GENTLE ART OF BLACKMAIL      _46_', '7 MR. MCGRATH REFUSES AN INVITATION      _57_', '8 A DEAD MAN      _66_', '9 ANTHONY DISPOSES OF A BODY      _74_', '10 CHIMNEYS      _83_', '11 SUPERINTENDENT BATTLE ARRIVES      _94_', '12 ANTHONY TELLS HIS STORY       _100_', '13 THE AMERICAN VISITOR      _110_', '14 MAINLY POLITICAL AND FINANCIAL      _116_', '15 THE FRENCH STRANGER      _125_', '16 TEA IN THE SCHOOLROOM      _138_', '17 A MIDNIGHT ADVENTURE      _150_', '18 SECOND MIDNIGHT ADVENTURE      _159_', '19 SECRET HISTORY      _170_', '20 BATTLE AND ANTHONY CONFER      _181_', '21 MR. ISAACSTEIN’S SUIT-CASE      _188_', '22 THE RED SIGNAL      _199_', '23 ENCOUNTER IN THE ROSE GARDEN      _212_', '24 THE HOUSE AT DOVER      _222_', '25 TUESDAY NIGHT AT CHIMNEYS      _230_', '26 THE 13TH OF OCTOBER      _238_', '27 THE 13TH OF OCTOBER (_contd._)      _244_', '28 KING VICTOR      _254_', '29 FURTHER EXPLANATIONS      _259_', '30 ANTHONY SIGNS ON FOR A NEW JOB      _264_', '31 SUNDRY DETAILS      _271_', '*       *       *       *       *'], total: 32)
Chapter list for The Missing Will (ID 12): text '“That was ', chapters: ['*       *       *       *       *'], total: 1)

With printing out the results, I found the problem that chapter lists can have duplicates in the sense that some books have additionally page numbers, extra spaces and/or additionl elements in the table of contents, while they are not present in the chapter titles at the beginning of each chapter. Therefore, I can have a doubled number of chapters and my chapter extraction function as well fining the main content of the book will not work well.

This problem happens with books 2, 3, 6 and 11. Book 7 gets also processed in a wrong way leaving out some of the chapters, although they could be identified with my function. Therefore, I will combine a common dataset from the "normal" books to this point to create an index, later I will add the rest after processing them separately.

In [ ]:
normal_book_ids = [0, 1, 4, 5, 8, 9, 10, 12]

for i in normal_book_ids:
    try:
        #get book data from DataFrame row
        book_text = df.iloc[i]["content"]
        book_title = df.iloc[i]["book_title"]
        book_id = int(df.iloc[i]["book_id"]) #otherwise it looks like np.int64(4)

        #removing metadata
        book_wo_metadata = delete_metadata(book_text)

        #generating a unique chapter list for each book
        chapter_list = find_chapters(book_wo_metadata, chapter_regex)

        #finding the main content for each book (excluding the table of contents)
        book_main_content = find_main_book_content(book_wo_metadata, chapter_list)

        #checking whether all functions worked in the right way
        print(f"Chapter list for {book_title} (ID {book_id}): text '{book_main_content[:10]}', chapters: {chapter_list}, total: {len(chapter_list)})")

        #splitting into chapters and paragraphs
        paragraph_num = 7
        book_df = extract_chapters_and_paragraphs(book_main_content, chapter_list, book_id, book_title, paragraph_num)

        almost_final_df = pd.concat([final_df, book_df], ignore_index=True)

    except Exception as e:
        print(f"[ERROR] Book ID {df.iloc[i]['book_id']} - {df.iloc[i]['book_title']}: {e}")

Chapter list for The man in the Brown Suit (ID 0): text '“MYSTERY O', chapters: ['I SHOULD SOME DAY WRITE THE', 'PROLOGUE', 'CHAPTER I', 'CHAPTER II', 'CHAPTER III', 'CHAPTER IV', 'CHAPTER V', 'CHAPTER VI', 'CHAPTER VII', 'CHAPTER VIII', 'CHAPTER IX', '17. How the number persisted. It was on the 17th I had sailed from', 'CHAPTER X', 'CHAPTER XI', 'CHAPTER XII', 'CHAPTER XIII', 'CHAPTER XIV', 'CHAPTER XV', 'CHAPTER XVI', 'CHAPTER XVII', 'CHAPTER XVIII', 'CHAPTER XIX', 'CHAPTER XX', 'CHAPTER XXI', 'CHAPTER XXII', 'CHAPTER XXIII', 'CHAPTER XXIV', 'CHAPTER XXV', 'CHAPTER XXVI', 'CHAPTER XXVII', 'CHAPTER XXVIII', 'CHAPTER XXIX', 'CHAPTER XXX', 'CHAPTER XXXI', 'CHAPTER XXXII', 'CHAPTER XXXIII', 'CHAPTER XXXIV', 'CHAPTER XXXV', 'CHAPTER XXXVI'], total: 39)
Chapter list for The Hunter's Lodge Case (ID 1): text 'To this I ', chapters: ['*       *       *       *       *'], total: 1)
Chapter list for The Mystery of the Blue Train (ID 4): text 'Cast of Ch', chapters: ['1. The Man with the White Hair', '2. M. le Marquis', '3. Heart of Fire', '4. In Curzon Street', '5. A Useful Gentleman', '6. Mirelle', '7. Letters', '8. Lady Tamplin Writes a Letter', '9. An Offer Refused', '10. On the Blue Train', '11. Murder', '12. At the Villa Marguerite', '13. Van Aldin Gets a Telegram', "14. Ada Mason's Story", '15. The Comte de la Roche', '16. Poirot Discusses the Case', '17. An Aristocratic Gentleman', '18. Derek Lunches', '19. An Unexpected Visitor', '20. Katherine Makes a Friend', '21. At the Tennis', '22. M. Papopolous Breakfasts', '23. A New Theory', '24. Poirot Gives Advice', '25. Defiance', '26. A Warning', '27. Interview with Mirelle', '28. Poirot Plays the Squirrel', '29. A Letter From Home', '30. Miss Viner Gives Judgment', '31. Mr. Aarons Lunches', '32. Katherine and Poirot Compare Notes', '33. A New Theory', '34. The Blue Train Again', '35. Explanations', '36. By the Sea'], total: 36)
Chapter list for Poirot Investigates (ID 5): text 'POIROT INV', chapters: ['I The Adventure of “The Western Star”', 'II The Tragedy at Marsdon Manor', 'III The Adventure of the Cheap Flat', 'IV The Mystery of Hunter’s Lodge', 'V The Million Dollar Bond Robbery', 'VI The Adventure of the Egyptian Tomb', 'VII Jewel Robbery at the _Grand Metropolitan_', 'VIII The Kidnapped Prime Minister', 'IX The Disappearance of Mr. Davenheim', 'X The Adventure of the Italian Nobleman', 'XI The Case of the Missing Will'], total: 11)
Chapter list for The Murder on the Links (ID 8): text '1 A Fellow', chapters: ['1 A Fellow Traveller', '2 An Appeal for Help', '3 At the Villa Geneviève', '4 The Letter Signed “Bella”', '5 Mrs. Renauld’s Story', '6 The Scene of the Crime', '7 The Mysterious Madame Daubreuil', '8 An Unexpected Meeting', '9 M. Giraud Finds Some Clues', '10 Gabriel Stonor', '11 Jack Renauld', '12 Poirot Elucidates Certain Points', '13 The Girl with the Anxious Eyes', '14 The Second Body', '15 A Photograph', '16 The Beroldy Case', '17 We Make Further Investigations', '18 Giraud Acts', '19 I Use My Grey Cells', '20 An Amazing Statement', '21 Hercule Poirot on the Case!', '22 I Find Love', '23 Difficulties Ahead', '25 An Unexpected Dénouement', '26 I Receive a Letter', '27 Jack Renauld’s Story', '28 Journey’s End'], total: 27)
Chapter list for The Mysterious Affair at Styles (ID 9): text 'CHAPTER I.', chapters: ['CHAPTER I. I GO TO STYLES', 'CHAPTER II. THE 16TH AND 17TH OF JULY', 'CHAPTER III. THE NIGHT OF THE TRAGEDY', 'CHAPTER IV. POIROT INVESTIGATES', 'CHAPTER V. “IT ISN’T STRYCHNINE, IS IT?”', 'CHAPTER VI. THE INQUEST', 'CHAPTER VII. POIROT PAYS HIS DEBTS', 'CHAPTER VIII. FRESH SUSPICIONS', 'CHAPTER IX. DR. BAUERSTEIN', 'CHAPTER X. THE ARREST', 'CHAPTER XI. THE CASE FOR THE PROSECUTION', 'CHAPTER XII. THE LAST LINK', 'CHAPTER XIII. POIROT EXPLAINS'], total: 13)
Chapter list for The Plymouth Express Affair (ID 10): text '“Mon ami,”', chapters: ['*       *       *       *       *'], total: 1)
Chapter list for The Missing Will (ID 12): text '“That was ', chapters: ['*       *       *       *       *'], total: 1)

In [ ]:
# Save to CSV
almost_final_df.to_csv("processed_books.csv", index=False)

In [ ]:
almost_final_df.to_excel("processed_books.xlsx", index=False)

In [ ]:
almost_final_df

### Tokenization and Lemmatisation

For tokenisation and preprocessing I have used libraries NLTK and SpaCy as both of them useful feutues for prepeocessing.

From SpaCy, I have chosen the trf model as it is said to be the most precise from the three they have for English. However, later I will try out different one to see of he work better on my data.

In [20]:
import pandas as pd

In [21]:
#loading back the dataset
almost_final_df = pd.read_csv("processed_books.csv")

In [38]:
! python -m spacy download en_core_web_trf

Collecting en-core-web-trf==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.8.0/en_core_web_trf-3.8.0-py3-none-any.whl (457.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 457.4/457.4 MB 3.6 MB/s eta 0:00:00
Collecting spacy-curated-transformers<1.0.0,>=0.2.2 (from en-core-web-trf==3.8.0)
  Downloading spacy_curated_transformers-0.3.0-py2.py3-none-any.whl.metadata (2.7 kB)
Collecting curated-transformers<0.2.0,>=0.1.0 (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading curated_transformers-0.1.1-py2.py3-none-any.whl.metadata (965 bytes)
Collecting curated-tokenizers<0.1.0,>=0.0.9 (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading curated_tokenizers-0.0.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.9 kB)
Requirement already satisfied: torch>=1.12.0 in /usr/local/lib/python3.11/dist-packages (from spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.6.0+cu124)
Requirement already satisfied: regex>=2022 in /usr/local/lib/python3.11/dist-packages (from curated-tokenizers<0.1.0,>=0.0.9->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2024.11.6)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.18.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (4.13.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2025.3.2)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.12.0->spacy-curated-transformers<1.0.0,>=0.2.2->en-core-web-trf==3.8.0) (3.0.2)
Downloading spacy_curated_transformers-0.3.0-py2.py3-none-any.whl (236 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 236.3/236.3 kB 14.2 MB/s eta 0:00:00
Downloading curated_tokenizers-0.0.9-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (735 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 735.6/735.6 kB 46.8 MB/s eta 0:00:00
Downloading curated_transformers-0.1.1-py2.py3-none-any.whl (25 kB)
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.4 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 74.1 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 66.3 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 50.8 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.9 MB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.5 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.2 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.8 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 6.1 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 57.5 MB/s eta 0:00:00
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, curated-tokenizers, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, curated-transformers, spacy-curated-transformers, en-core-web-trf
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
Successfully installed curated-tokenizers-0.0.9 curated-transformers-0.1.1 en-core-web-trf-3.8.0 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 spacy-curated-transformers-0.3.0
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_trf')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [39]:
import spacy
nlp = spacy.load("en_core_web_trf")

import en_core_web_trf
nlp = en_core_web_trf.load()

doc = nlp("This is a sentence.")
print([(w.text, w.pos_) for w in doc])

[('This', 'PRON'), ('is', 'AUX'), ('a', 'DET'), ('sentence', 'NOUN'), ('.', 'PUNCT')]

In [ ]:
import spacy
print(spacy.info())  # Lists installed models

{'spacy_version': '3.8.5', 'location': '/usr/local/lib/python3.11/dist-packages/spacy', 'platform': 'Linux-6.1.123+-x86_64-with-glibc2.35', 'python_version': '3.11.12', 'pipelines': {'en_core_web_trf': '3.8.0', 'en_core_web_sm': '3.8.0'}}

In [ ]:
processed_book_1 = nlp(book_1_main_content) #processed book from the part with experimenting with one book

In [ ]:
# Tokenization

tokens = []

for token in processed_book_1:
  tokens.append(token.text)

unique_tokens = set(tokens)

print(tokens[:200])

#Lemmatisation

lemmatised_tokens = []

for token in processed_book_1:
  lemmatised_tokens.append(token.lemma_)

print(lemmatised_tokens[:200])
print("\n")

print(f'Number of tokens in the preproccessed text: {len(tokens)}')
print(f'Number of unique tokens  in the preproccessed text: {len(unique_tokens)}')
print(f'Number of lemmatised tokens in the preproccessed text: {len(tokens)}')

['1', 'A', 'Fellow', 'Traveller', '\n', 'I', 'believe', 'that', 'a', 'well', '-', 'known', 'anecdote', 'exists', 'to', 'the', 'effect', 'that', 'a', 'young', '\n', 'writer', ',', 'determined', 'to', 'make', 'the', 'commencement', 'of', 'his', 'story', 'forcible', 'and', '\n', 'original', 'enough', 'to', 'catch', 'and', 'rivet', 'the', 'attention', 'of', 'the', 'most', 'blasé', 'of', '\n', 'editors', ',', 'penned', 'the', 'following', 'sentence', ':', '\n', '“', '‘', 'Hell', '!', '’', 'said', 'the', 'Duchess', '.', '”', '\n', 'Strangely', 'enough', ',', 'this', 'tale', 'of', 'mine', 'opens', 'in', 'much', 'the', 'same', 'fashion', '.', '\n', 'Only', 'the', 'lady', 'who', 'gave', 'utterance', 'to', 'the', 'exclamation', 'was', 'not', 'a', 'Duchess', '!', '\n', 'It', 'was', 'a', 'day', 'in', 'early', 'June', '.', 'I', 'had', 'been', 'transacting', 'some', 'business', 'in', '\n', 'Paris', 'and', 'was', 'returning', 'by', 'the', 'morning', 'service', 'to', 'London', 'where', 'I', 'was', '\n', 'still', 'sharing', 'rooms', 'with', 'my', 'old', 'friend', ',', 'the', 'Belgian', 'ex', '-', 'detective', ',', '\n', 'Hercule', 'Poirot', '.', '\n', 'The', 'Calais', 'express', 'was', 'singularly', 'empty', '—', 'in', 'fact', ',', 'my', 'own', 'compartment', '\n', 'held', 'only', 'one', 'other', 'traveller', '.', 'I', 'had', 'made', 'a', 'somewhat', 'hurried', 'departure', '\n', 'from', 'the', 'hotel', 'and', 'was', 'busy', 'assuring', 'myself', 'that', 'I', 'had', 'duly', 'collected', '\n', 'all', 'my', 'traps', 'when', 'the', 'train', 'started', '.', 'Up', 'till', 'then', 'I']
['1', 'a', 'Fellow', 'Traveller', '\n', 'I', 'believe', 'that', 'a', 'well', '-', 'know', 'anecdote', 'exist', 'to', 'the', 'effect', 'that', 'a', 'young', '\n', 'writer', ',', 'determined', 'to', 'make', 'the', 'commencement', 'of', 'his', 'story', 'forcible', 'and', '\n', 'original', 'enough', 'to', 'catch', 'and', 'rivet', 'the', 'attention', 'of', 'the', 'most', 'blasé', 'of', '\n', 'editor', ',', 'pen', 'the', 'follow', 'sentence', ':', '\n', '"', "'", 'hell', '!', "'", 'say', 'the', 'Duchess', '.', '"', '\n', 'strangely', 'enough', ',', 'this', 'tale', 'of', 'mine', 'open', 'in', 'much', 'the', 'same', 'fashion', '.', '\n', 'only', 'the', 'lady', 'who', 'give', 'utterance', 'to', 'the', 'exclamation', 'be', 'not', 'a', 'Duchess', '!', '\n', 'it', 'be', 'a', 'day', 'in', 'early', 'June', '.', 'I', 'have', 'be', 'transact', 'some', 'business', 'in', '\n', 'Paris', 'and', 'be', 'return', 'by', 'the', 'morning', 'service', 'to', 'London', 'where', 'I', 'be', '\n', 'still', 'share', 'room', 'with', 'my', 'old', 'friend', ',', 'the', 'belgian', 'ex', '-', 'detective', ',', '\n', 'Hercule', 'Poirot', '.', '\n', 'the', 'Calais', 'express', 'be', 'singularly', 'empty', '—', 'in', 'fact', ',', 'my', 'own', 'compartment', '\n', 'hold', 'only', 'one', 'other', 'traveller', '.', 'I', 'have', 'make', 'a', 'somewhat', 'hurried', 'departure', '\n', 'from', 'the', 'hotel', 'and', 'be', 'busy', 'assure', 'myself', 'that', 'I', 'have', 'duly', 'collect', '\n', 'all', 'my', 'trap', 'when', 'the', 'train', 'start', '.', 'up', 'till', 'then', 'I']


Number of tokens in the preproccessed text: 89773
Number of unique tokens  in the preproccessed text: 6416
Number of lemmatised tokens in the preproccessed text: 89773

In [ ]:
book_paragraphs = almost_final_df[almost_final_df['book_title'] == "The Murder on the Links"]  #I want to see if the tokens get different from the ones
book_paragraphs

,book_id,book_title,chapter_id,chapter_title,paragraph_id,paragraph_text
672,8,The Murder on the Links,1,1 A Fellow Traveller,1,I believe that a well-known anecdote exists to...
673,8,The Murder on the Links,1,1 A Fellow Traveller,2,"I looked up now, frowning slightly, into a pre..."
674,8,The Murder on the Links,1,1 A Fellow Traveller,3,"was certainly all that I most disliked, but th..."
675,8,The Murder on the Links,1,1 A Fellow Traveller,4,"begged, “don’t get mad with me.” “I shan’t. I ..."
676,8,The Murder on the Links,1,1 A Fellow Traveller,5,"me was not without its charm, and I enjoyed se..."
...,...,...,...,...,...,...
856,8,The Murder on the Links,27,28 Journey’s End,3,"type as her mother. I doubt, too, whether she ..."
857,8,The Murder on the Links,27,28 Journey’s End,4,But I had not one single proof against her! “A...
858,8,The Murder on the Links,27,28 Journey’s End,5,pass to her son. But it would have been suicid...
859,8,The Murder on the Links,27,28 Journey’s End,6,"And yet, do you know, Hastings, I doubt if his..."
860,8,The Murder on the Links,27,28 Journey’s End,7,sailing for South America almost immediately. ...

In [ ]:
full_text = ' '.join(book_paragraphs['paragraph_text'].astype(str).tolist())
full_text[:100]

'I believe that a well-known anecdote exists to the effect that a young writer, determined to make the commencement of his story forcible and original enough to catch and rivet the attention of the most blasé of editors, penned the following sentence: “‘Hell!’ said the Duchess.” Strangely enough, this tale of mine opens in much the same fashion. Only the lady who gave utterance to the exclamation was not a Duchess! It was a day in early June. I had been transacting some business in Paris and was returning by the morning service to London where I was still sharing rooms with my old friend, the Belgian ex-detective, Hercule Poirot. The Calais express was singularly empty—in fact, my own compartment held only one other traveller. I had made a somewhat hurried departure from the hotel and was busy assuring myself that I had duly collected all my traps when the train started. Up till then I had hardly noticed my companion, but I was now violently recalled to the fact of her existence. Jumping up from her seat, she let down the window and stuck her head out, withdrawing it a moment later with the brief and forcible ejaculation “Hell!” Now I am old-fashioned. A woman, I consider, should be womanly. I have no patience with the modern neurotic girl who jazzes from morning to night, smokes like a chimney, and uses language which would make a Billingsgate fishwoman blush! I looked up now, frowning slightly, into a pretty, impudent face, surmounted by a rakish little red hat. A thick cluster of black curls hid each ear. I judged that she was little more than seventeen, but her face was covered with powder, and her lips were quite impossibly scarlet. Nothing abashed, she returned my glance, and executed an expressive grimace. “Dear me, we’ve shocked the kind gentleman!” she observed to an imaginary audience. “I apologize for my language! Most unladylike, and all that, but Oh, Lord, there’s reason enough for it! Do you know I’ve lost my only sister?” “Really?” I said politely. “How unfortunate.” “He disapproves!” remarked the lady. “He disapproves utterly—of me, and my sister—which last is unfair, because he hasn’t seen her!” I opened my mouth, but she forestalled me. “Say no more! Nobody loves me! I shall go into the garden and eat worms! Boohoo! I am crushed!” She buried herself behind a large comic French paper. In a minute or two I saw her eyes stealthily peeping at me over the top. In spite of myself I could not help smiling, and in a minute she had tossed the paper aside, and had burst into a merry peal of laughter. “I knew you weren’t such a mutt as you looked,” she cried. Her laughter was so infectious that I could not help joining in, though I hardly cared for the word “mutt.” The girl was certainly all that I most disliked, but that was no reason why I should make myself ridiculous by my attitude. I prepared to unbend. After all, she was decidedly pretty.… “There! Now we’re friends!” declared the minx. “Say you’re sorry about my sister—” “I am desolated!” “That’s a good boy!” “Let me finish. I was going to add that, although I am desolated, I can manage to put up with her absence very well.” I made a little bow. But this most unaccountable of damsels frowned and shook her head. “Cut it out. I prefer the ‘dignified disapproval’ stunt. Oh, your face! ‘Not one of us,’ it said. And you were right there—though, mind you, it’s pretty hard to tell nowadays. It’s not every one who can distinguish between a demi and a duchess. There now, I believe I’ve shocked you again! You’ve been dug out of the backwoods, you have. Not that I mind that. We could do with a few more of your sort. I just hate a fellow who gets fresh. It makes me mad.” She shook her head vigorously. “What are you like when you’re mad?” I inquired with a smile. “A regular little devil! Don’t care what I say, or what I do, either! I nearly did a chap in once. Yes, really. He’d have deserved it too. Italian blood I’ve got. I shall get into trouble one of these days.” “Well,” I begged, “don’t get mad with me.” “I shan’t. I like you—did the first moment I set eyes on you. But you looked so disapproving that I never thought we should make friends.” “Well, we have. Tell me something about yourself.” “I’m an actress. No—not the kind you’re thinking of, lunching at the Savoy covered with jewellery, and with their photograph in every paper saying how much they love Madame So and So’s face cream. I’ve been on the boards since I was a kid of six—tumbling.” “I beg your pardon,” I said puzzled. “Haven’t you seen child acrobats?” “Oh, I understand.” “I’m American born, but I’ve spent most of my life in England. We got a new show now—” “We?” “My sister and I. Sort of song and dance, and a bit of patter, and a dash of the old business thrown in. It’s quite a new idea, and it hits them every time. There’s to be money in it—” My new acquaintance leaned forward, and discoursed volubly, a great many of her terms being quite unintelligible to me. Yet I found myself evincing an increasing interest in her. She seemed such a curious mixture of child and woman. Though perfectly worldly-wise, and able, as she expressed it, to take care of herself, there was yet something curiously ingenuous in her single-minded attitude towards life, and her whole-hearted determination to “make good.” This glimpse of a world unknown to me was not without its charm, and I enjoyed seeing her vivid little face light up as she talked. We passed through Amiens. The name awakened many memories. My companion seemed to have an intuitive knowledge of what was in my mind. “Thinking of the War?” I nodded. “You were through it, I suppose?” “Pretty well. I was wounded once, and after the Somme they invalided me out altogether. I had a half fledged Army job for a bit. I’m a sort of private secretary now to an M. P.” “My! That’s brainy!” “No, it isn’t. There’s really awfully little to do. Usually a couple of hours every day sees me through. It’s dull work too. In fact, I don’t know what I should do if I hadn’t got something to fall back upon.” “Don’t say you collect bugs!” “No. I share rooms with a very interesting man. He’s a Belgian—an ex-detective. He’s set up as a private detective in London, and he’s doing extraordinarily well. He’s really a very marvellous little man. Time and again he has proved to be right where the official police have failed.” My companion listened with widening eyes. “Isn’t that interesting, now? I just adore crime. I go to all the mysteries on the movies. And when there’s a murder on I just devour the papers.” “Do you remember the Styles Case?” I asked. “Let me see, was that the old lady who was poisoned? Somewhere down in Essex?” I nodded. “That was Poirot’s first big case. Undoubtedly, but for him, the murderer would have escaped scot-free. It was a most wonderful bit of detective work.” Warming to my subject, I ran over the heads of the affair, working up to the triumphant and unexpected dénouement. The girl listened spellbound. In fact, we were so absorbed that the train drew into Calais station before we realized it. “My goodness gracious me!” cried my companion. “Where’s my powder-puff?” She proceeded to bedaub her face liberally, and then applied a stick of lip salve to her lips, observing the effect in a small pocket glass, and betraying not the faintest sign of self-consciousness. “I say,” I hesitated. “I dare say it’s cheek on my part, but why do all that sort of thing?” The girl paused in her operations, and stared at me with undisguised surprise. “It isn’t as though you weren’t so pretty that you can afford to do without it,” I said stammeringly. “My dear boy! I’ve got to do it. All the girls do. Think I want to look like a little frump up from the country?” She took one last look in the mirror, smiled approval, and put it and her vanity-box away in her bag. “That’s better. Keeping up appearances is a bit of a fag, I grant, but if a girl respects herself it’s up to her not to let herself get slack.” To this essentially moral sentiment, I had no reply. A point of view makes a great difference. I secured a couple of porters, and we alighted on the platform. My companion held out her hand. “Good-bye, and I’ll mind my language better in future.” “Oh, but surely you’ll let me look after you on the boat?” “Mayn’t be on the boat. I’ve got to see whether that sister of mine got aboard after all anywhere. But thanks all the same.” “Oh, but we’re going to meet again, surely? I—” I hesitated. “I want to meet your sister.” We both laughed. “That’s real nice of you. I’ll tell her what you say. But I don’t fancy we’ll meet again. You’ve been very good to me on the journey, especially after I cheeked you as I did. But what your face expressed first thing is quite true. I’m not your kind. And that brings trouble—_I___ know that well enough.…” Her face changed. For the moment all the light-hearted gaiety died out of it. It looked angry—revengeful.… “So good-bye,” she finished, in a lighter tone. “Aren’t you even going to tell me your name?” I cried, as she turned away. She looked over her shoulder. A dimple appeared in each cheek. She was like a lovely picture by Greuze. “Cinderella,” she said, and laughed. But little did I think when and how I should see Cinderella again. It was five minutes past nine when I entered our joint sitting-room for breakfast on the following morning. My friend Poirot, exact to the minute as usual, was just tapping the shell of his second egg. He beamed upon me as I entered. “You have slept well, yes? You have recovered from the crossing so terrible? It is a marvel, almost you are exact this morning. _Pardon___, but your tie is not symmetrical. Permit that I rearrange him.” Elsewhere, I have described Hercule Poirot. An extraordinary little man! Height, five feet four inches, egg-shaped head carried a little to one side, eyes that shone green when he was excited, stiff military moustache, air of dignity immense! He was neat and dandified in appearance. For neatness of any kind, he had an absolute passion. To see an ornament set crooked, or a speck of dust, or a slight disarray in one’s attire, was torture to the little man until he could ease his feelings by remedying the matter. “Order” and “Method” were his gods. He had a certain disdain for tangible evidence, such as footprints and cigarette ash, and would maintain that, taken by themselves, they would never enable a detective to solve a problem. Then he would tap his egg-shaped head with absurd complacency, and remark with great satisfaction: “The true work, it is done from _within___. _The little grey cells___—remember always the little grey cells, _mon ami!___” I slipped into my seat, and remarked idly, in answer to Poirot’s greeting, that an hour’s sea passage from Calais to Dover could hardly be dignified by the epithet “terrible.” Poirot waved his egg-spoon in vigorous refutation of my remark. “_Du tout!___ If for an hour one experiences sensations and emotions of the most terrible, one has lived many hours! Does not one of your English poets say that time is counted, not by hours, but by heart-beats?” “I fancy Browning was referring to something more romantic than sea sickness, though.” “Because he was an Englishman, an Islander to whom _la Manche___ was nothing. Oh, you English! With _nous autres___ it is different. Figure to yourself that a lady of my acquaintance at the beginning of the war fled to Ostend. There she had a terrible crisis of the nerves. Impossible to escape further except by crossing the sea! And she had a horror—_mais une horreur!___—of the sea! What was she to do? Daily _les Boches___ were drawing nearer. Imagine to yourself the terrible situation!” “What did she do?” I inquired curiously. “Fortunately her husband was _homme pratique___. He was also very calm, the crises of the nerves, they affected him not. _Il l’a emportée simplement!___ Naturally when she reached England she was prostrate, but she still breathed.” Poirot shook his head seriously. I composed my face as best I could. Suddenly he stiffened and pointed a dramatic finger at the toast rack. “Ah, par exemple, c’est trop fort!” he cried. “What is it?” “This piece of toast. You remark him not?” He whipped the offender out of the rack, and held it up for me to examine. “Is it square? No. Is it a triangle? Again no. Is it even round? No. Is it of any shape remotely pleasing to the eye? What symmetry have we here? None.” “It’s cut from a cottage loaf,” I explained soothingly. Poirot threw me a withering glance. “What an intelligence has my friend Hastings!” he exclaimed sarcastically. “Comprehend you not that I have forbidden such a loaf—a loaf haphazard and shapeless, that no baker should permit himself to bake!” I endeavoured to distract his mind. “Anything interesting come by the post?” Poirot shook his head with a dissatisfied air. “I have not yet examined my letters, but nothing of interest arrives nowadays. The great criminals, the criminals of method, they do not exist. The cases I have been employed upon lately were _banal___ to the last degree. In verity I am reduced to recovering lost lap-dogs for fashionable ladies! The last problem that presented any interest was that intricate little affair of the Yardly diamond, and that was—how many months ago, my friend?” He shook his head despondently, and I roared with laughter. “Cheer up, Poirot, the luck will change. Open your letters. For all you know, there may be a great Case looming on the horizon.” Poirot smiled, and taking up the neat little letter opener with which he opened his correspondence he slit the tops of the several envelopes that lay by his plate. “A bill. Another bill. It is that I grow extravagant in my old age. Aha! a note from Japp.” “Yes?” pricked up my ears. The Scotland Yard Inspector had more than once introduced us to an interesting case. “He merely thanks me (in his fashion) for a little point in the Aberystwyth Case on which I was able to set him right. I am delighted to have been of service to him.” “How does he thank you?” I asked curiously, for I knew my Japp. “He is kind enough to say that I am a wonderful sport for my age, and that he was glad to have had the chance of letting me in on the case.” This was so typical of Japp, that I could not forbear a chuckle. Poirot continued to read his correspondence placidly. “A suggestion that I should give a lecture to our local boy scouts. The Countess of Forfanock will be obliged if I will call and see her. Another lap-dog without doubt! And now for the last. Ah—” I looked up, quick to notice the change of tone. Poirot was reading attentively. In a minute he tossed the sheet over to me. “This is out of the ordinary, _mon ami___. Read for yourself.” The letter was written on a foreign type of paper, in a bold characteristic hand: “Villa Geneviève Merlinville-sur-Mer France “_Dear Sir___, “I am in need of the services of a detective and, for reasons which I will give you later, do not wish to call in the official police. I have heard of you from several quarters, and all reports go to show that you are not only a man of decided ability, but one who also knows how to be discreet. I do not wish to trust details to the post, but, on account of a secret I possess, I go in daily fear of my life. I am convinced that the danger is imminent, and therefore I beg that you will lose no time in crossing to France. I will send a car to meet you at Calais, if you will wire me when you are arriving. I shall be obliged if you will drop all cases you have on hand, and devote yourself solely to my interests. I am prepared to pay any compensation necessary. I shall probably need your services for a considerable period of time, as it may be necessary for you to go out to Santiago, where I spent several years of my life. I shall be content for you to name your own fee. “Assuring you once more that the matter is _urgent___, “Yours faithfully “P. T. RENAULD.” Below the signature was a hastily scrawled line, almost illegible: “For God’s sake, come!” I handed the letter back with quickened pulses. “At last!” I said. “Here is something distinctly out of the ordinary.” “Yes, indeed,” said Poirot meditatively. “You will go of course,” I continued. Poirot nodded. He was thinking deeply. Finally he seemed to make up his mind, and glanced up at the clock. His face was very grave. “See you, my friend, there is no time to lose. The Continental express leaves Victoria at 11 o’clock. Do not agitate yourself. There is plenty of time. We can allow ten minutes for discussion. You accompany me, _n’est-ce pas?___” “Well—” “You told me yourself that your employer needed you not for the next few weeks.” “Oh, that’s all right. But this Mr. Renauld hints strongly that his business is private.” “Ta-ta-ta. I will manage M. Renauld. By the way, I seem to know the name?” “There’s a well-known South American millionaire fellow. His name’s Renauld. I don’t know whether it could be the same.” “But without doubt. That explains the mention of Santiago. Santiago is in Chile, and Chile it is in South America! Ah, but we progress finely.” “Dear me, Poirot,” I said, my excitement rising, “I smell some goodly shekels in this. If we succeed, we shall make our fortunes!” “Do not be too sure of that, my friend. A rich man and his money are not so easily parted. Me, I have seen a well-known millionaire turn out a tramful of people to seek for a dropped halfpenny.” I acknowledged the wisdom of this. “In any case,” continued Poirot, “it is not the money which attracts me here. Certainly it will be pleasant to have _carte blanche___ in our investigations; one can be sure that way of wasting no time, but it is something a little bizarre in this problem which arouses my interest. You remarked the postscript? How did it strike you?” I considered. “Clearly he wrote the letter keeping himself well in hand, but at the end his self-control snapped and, on the impulse of the moment, he scrawled those four desperate words.” But my friend shook his head energetically. “You are in error. See you not that while the ink of the signature is nearly black, that of the postscript is quite pale?” “Well?” I said puzzled. “_Mon Dieu, mon ami___, but use your little grey cells! Is it not obvious? M. Renauld wrote his letter. Without blotting it, he reread it carefully. Then, not on impulse, but deliberately, he added those last words, and blotted the sheet.” “But why?” “_Parbleu!___ so that it should produce the effect upon me that it has upon you.” “What?” “_Mais, oui___—to make sure of my coming! He reread the letter and was dissatisfied. It was not strong enough!” He paused, and then added softly, his eyes shining with that green light that always betokened inward excitement: “And so, _mon ami___, since that postscript was added, not on impulse, but soberly, in cold blood, the urgency is very great, and we must reach him as soon as possible.” “Merlinville,” I murmured thoughtfully. “I’ve heard of it, I think.” Poirot nodded. “It is a quiet little place—but chic! It lies about midway between Bolougne and Calais. It is rapidly becoming the fashion. Rich English people who wish to be quiet are taking it up. M. Renauld has a house in England, I suppose?” “Yes, in Rutland Gate, as far as I remember. Also a big place in the country, somewhere in Hertfordshire. But I really know very little about him, he doesn’t do much in a social way. I believe he has large South American interests in the City, and has spent most of his life out in Chile and the Argentino.” “Well, we shall hear all details from the man himself. Come, let us pack. A small suit-case each, and then a taxi to Victoria.” “And the Countess?” I inquired with a smile. “Ah! _je m’en fiche!___ Her case was certainly not interesting.” “Why so sure of that?” “Because in that case she would have come, not written. A woman cannot wait—always remember that, Hastings.” Eleven o’clock saw our departure from Victoria on our way to Dover. Bef

In [ ]:
processed_book_1_df = nlp(full_text)

In [ ]:
# Tokenization

tokens = []

for token in processed_book_1_df:
  tokens.append(token.text)

unique_tokens = set(tokens)

print(tokens[:200])

#Lemmatisation

lemmatised_tokens = []

for token in processed_book_1_df:
  lemmatised_tokens.append(token.lemma_)

print(lemmatised_tokens[:200])
print("\n")

print(f'Number of tokens in the preproccessed text: {len(tokens)}')
print(f'Number of unique tokens  in the preproccessed text: {len(unique_tokens)}')
print(f'Number of lemmatised tokens in the preproccessed text: {len(tokens)}')

['I', 'believe', 'that', 'a', 'well', '-', 'known', 'anecdote', 'exists', 'to', 'the', 'effect', 'that', 'a', 'young', 'writer', ',', 'determined', 'to', 'make', 'the', 'commencement', 'of', 'his', 'story', 'forcible', 'and', 'original', 'enough', 'to', 'catch', 'and', 'rivet', 'the', 'attention', 'of', 'the', 'most', 'blasé', 'of', 'editors', ',', 'penned', 'the', 'following', 'sentence', ':', '“', '‘', 'Hell', '!', '’', 'said', 'the', 'Duchess', '.', '”', 'Strangely', 'enough', ',', 'this', 'tale', 'of', 'mine', 'opens', 'in', 'much', 'the', 'same', 'fashion', '.', 'Only', 'the', 'lady', 'who', 'gave', 'utterance', 'to', 'the', 'exclamation', 'was', 'not', 'a', 'Duchess', '!', 'It', 'was', 'a', 'day', 'in', 'early', 'June', '.', 'I', 'had', 'been', 'transacting', 'some', 'business', 'in', 'Paris', 'and', 'was', 'returning', 'by', 'the', 'morning', 'service', 'to', 'London', 'where', 'I', 'was', 'still', 'sharing', 'rooms', 'with', 'my', 'old', 'friend', ',', 'the', 'Belgian', 'ex', '-', 'detective', ',', 'Hercule', 'Poirot', '.', 'The', 'Calais', 'express', 'was', 'singularly', 'empty', '—', 'in', 'fact', ',', 'my', 'own', 'compartment', 'held', 'only', 'one', 'other', 'traveller', '.', 'I', 'had', 'made', 'a', 'somewhat', 'hurried', 'departure', 'from', 'the', 'hotel', 'and', 'was', 'busy', 'assuring', 'myself', 'that', 'I', 'had', 'duly', 'collected', 'all', 'my', 'traps', 'when', 'the', 'train', 'started', '.', 'Up', 'till', 'then', 'I', 'had', 'hardly', 'noticed', 'my', 'companion', ',', 'but', 'I', 'was', 'now', 'violently', 'recalled', 'to', 'the', 'fact', 'of', 'her', 'existence', '.']
['I', 'believe', 'that', 'a', 'well', '-', 'know', 'anecdote', 'exist', 'to', 'the', 'effect', 'that', 'a', 'young', 'writer', ',', 'determine', 'to', 'make', 'the', 'commencement', 'of', 'his', 'story', 'forcible', 'and', 'original', 'enough', 'to', 'catch', 'and', 'rivet', 'the', 'attention', 'of', 'the', 'most', 'blasé', 'of', 'editor', ',', 'pen', 'the', 'following', 'sentence', ':', '"', "'", 'hell', '!', "'", 'say', 'the', 'Duchess', '.', '"', 'strangely', 'enough', ',', 'this', 'tale', 'of', 'mine', 'open', 'in', 'much', 'the', 'same', 'fashion', '.', 'only', 'the', 'lady', 'who', 'give', 'utterance', 'to', 'the', 'exclamation', 'be', 'not', 'a', 'Duchess', '!', 'it', 'be', 'a', 'day', 'in', 'early', 'June', '.', 'I', 'have', 'be', 'transact', 'some', 'business', 'in', 'Paris', 'and', 'be', 'return', 'by', 'the', 'morning', 'service', 'to', 'London', 'where', 'I', 'be', 'still', 'share', 'room', 'with', 'my', 'old', 'friend', ',', 'the', 'belgian', 'ex', '-', 'detective', ',', 'Hercule', 'Poirot', '.', 'the', 'Calais', 'express', 'be', 'singularly', 'empty', '—', 'in', 'fact', ',', 'my', 'own', 'compartment', 'hold', 'only', 'one', 'other', 'traveller', '.', 'I', 'have', 'make', 'a', 'somewhat', 'hurried', 'departure', 'from', 'the', 'hotel', 'and', 'be', 'busy', 'assure', 'myself', 'that', 'I', 'have', 'duly', 'collect', 'all', 'my', 'trap', 'when', 'the', 'train', 'start', '.', 'up', 'till', 'then', 'I', 'have', 'hardly', 'notice', 'my', 'companion', ',', 'but', 'I', 'be', 'now', 'violently', 'recall', 'to', 'the', 'fact', 'of', 'her', 'existence', '.']


Number of tokens in the preproccessed text: 83177
Number of unique tokens  in the preproccessed text: 6358
Number of lemmatised tokens in the preproccessed text: 83177

I have foun that the number of tokens from combined parahraphs in my dataset is fewer than from the original dataset, asuumably because of the "\n" symbole used to combine the original book, while in the book rom the new dtaset a space was used.

For indexing, I will used the second mehtod of extracting the content of the books.

In [ ]:
# true casing

def truecase_text(text):
    doc = nlp(text)
    truecased_tokens = []
    for token in doc:
        if token.ent_type_ in ["PERSON", "GPE", "ORG"]:  # Named Entities should be capitalized
            truecased_tokens.append(token.text.title())
        elif token.is_sent_start:  # Capitalize the first word of each sentence
            truecased_tokens.append(token.text.capitalize())
        else:
            truecased_tokens.append(token.text.lower())

    return " ".join(truecased_tokens)

# Example usage
text = "john and mary went to new york city last summer."
truecased_text = truecase_text(text)
print(truecased_text)

John and Mary went to New York City last summer .

For the moment of creating an index, I will leave out the method of lemmatising and truecasing, later I will try them out if they improve the inforamtion retrieval.

The need if truecasing is still questionable for me as the lemmatisaion of SpaCy alreeady converts word forms into a typical case for them (preliminary proof below).

### Removing stopwords and punctuation

In [40]:
import nltk
import string
from nltk.corpus import stopwords

nltk.download('stopwords')
stop_words = set(stopwords.words('english'))
punctuation = set(string.punctuation)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

In [ ]:
print(stop_words)
print(punctuation)
print(type(punctuation))
print(len(punctuation))

{'should', 'against', "couldn't", "he's", "hasn't", 't', "they're", "wasn't", 'why', 'wasn', 'was', 'no', 'his', 'here', "won't", "hadn't", "i'd", 'of', 'yourselves', 'this', 'weren', "we're", 'didn', 'its', "you'll", "you've", 'when', 'some', "needn't", "you're", "she'd", 'before', 'doing', 'further', 'ourselves', 'y', 'on', 'she', 'does', 'in', "mightn't", 'the', 'below', 'or', 'if', 'been', 'each', 'my', "i'm", 'aren', 'o', 'itself', "they'll", "we'd", 'but', 'more', 'to', 'having', "it's", 'a', 'too', 'had', "he'd", 'at', 'll', "aren't", 'd', 'they', 'so', 'ma', 'our', 'because', "she's", "she'll", "he'll", "i've", "shan't", 'are', 'your', 'were', 'from', 'only', 'me', 'an', 'being', "it'll", 'while', 're', 'through', 'couldn', 'do', 'those', "they've", 'him', 'not', 'between', 'am', 'hasn', 'about', 'ain', 'don', 'up', 'both', 'then', 'once', 's', 'and', 'whom', "mustn't", 'again', 'who', 'mustn', "don't", 'needn', "we'll", "isn't", 'yourself', 'is', 'as', 'doesn', 'than', "they'd", 'you', 'myself', 'there', "wouldn't", 'with', "i'll", 'just', 'down', 'm', "shouldn't", 'won', 'hers', "doesn't", 'theirs', "we've", 'these', "it'd", 'mightn', 'few', 'such', 'yours', 'himself', 'them', "should've", 'over', 'most', 'under', 'nor', 'what', "you'd", 'i', 'now', 've', 'own', 'off', "didn't", 'be', 'her', "haven't", 'how', 'did', 'he', 'all', 'during', 'out', 'same', 'which', 'wouldn', 'other', 'has', 'shan', 'until', 'it', 'that', 'where', 'hadn', 'isn', "that'll", 'ours', 'we', 'shouldn', "weren't", 'above', 'very', 'themselves', 'haven', 'after', 'for', 'their', 'will', 'herself', 'by', 'can', 'into', 'have', 'any'}
{'”', '%', ':', '.', '@', '&', "'", '>', '}', ')', '^', '‘', '-', '`', '“', '’', '\\', '!', '[', '{', ']', '|', '+', ',', '/', '?', '_', ';', '*', '=', '#', '~', '"', '<', '$', '—', '('}
<class 'set'>
37

In [ ]:
# Removing punctutation and stopwords

clean_tokens = []
for token in tokens:
  if token in punctuation or token in stop_words:
    continue
  else:
    clean_tokens.append(token)

print(clean_tokens[:100])

clean_lemmatised_tokens = []
for token in lemmatised_tokens:
  if token in punctuation or token in stop_words:
    continue
  else:
    clean_lemmatised_tokens.append(token)

print(clean_lemmatised_tokens[:100])

print(len(tokens))
print(len(clean_tokens))
print(len(clean_lemmatised_tokens))

['I', 'believe', 'well', 'known', 'anecdote', 'exists', 'effect', 'young', 'writer', 'determined', 'make', 'commencement', 'story', 'forcible', 'original', 'enough', 'catch', 'rivet', 'attention', 'blasé', 'editors', 'penned', 'following', 'sentence', 'Hell', 'said', 'Duchess', 'Strangely', 'enough', 'tale', 'mine', 'opens', 'much', 'fashion', 'Only', 'lady', 'gave', 'utterance', 'exclamation', 'Duchess', 'It', 'day', 'early', 'June', 'I', 'transacting', 'business', 'Paris', 'returning', 'morning', 'service', 'London', 'I', 'still', 'sharing', 'rooms', 'old', 'friend', 'Belgian', 'ex', 'detective', 'Hercule', 'Poirot', 'The', 'Calais', 'express', 'singularly', 'empty', 'fact', 'compartment', 'held', 'one', 'traveller', 'I', 'made', 'somewhat', 'hurried', 'departure', 'hotel', 'busy', 'assuring', 'I', 'duly', 'collected', 'traps', 'train', 'started', 'Up', 'till', 'I', 'hardly', 'noticed', 'companion', 'I', 'violently', 'recalled', 'fact', 'existence', 'Jumping', 'seat']
['I', 'believe', 'well', 'know', 'anecdote', 'exist', 'effect', 'young', 'writer', 'determine', 'make', 'commencement', 'story', 'forcible', 'original', 'enough', 'catch', 'rivet', 'attention', 'blasé', 'editor', 'pen', 'following', 'sentence', 'hell', 'say', 'Duchess', 'strangely', 'enough', 'tale', 'mine', 'open', 'much', 'fashion', 'lady', 'give', 'utterance', 'exclamation', 'Duchess', 'day', 'early', 'June', 'I', 'transact', 'business', 'Paris', 'return', 'morning', 'service', 'London', 'I', 'still', 'share', 'room', 'old', 'friend', 'belgian', 'ex', 'detective', 'Hercule', 'Poirot', 'Calais', 'express', 'singularly', 'empty', 'fact', 'compartment', 'hold', 'one', 'traveller', 'I', 'make', 'somewhat', 'hurried', 'departure', 'hotel', 'busy', 'assure', 'I', 'duly', 'collect', 'trap', 'train', 'start', 'till', 'I', 'hardly', 'notice', 'companion', 'I', 'violently', 'recall', 'fact', 'existence', 'jump', 'seat', 'let', 'window', 'stick', 'head']
83177
37005
33224

Insepecting the out put of the removing the punctuation signs, I found some signs that were not present in the punctuation list, which I then added to it. These are '“', '‘', '’', '”', '—'.

In [41]:
new_signs = ['“', '‘', '’', '”', '—']

## 4. Cleaning and Preprocessing All Books

In [42]:
# functions for preprocessing

def preprocess_book(book, stop_words, punctuation, lemmatisation=False):
    clean_book_tokens = []
    processed_book = nlp(book)
    for token in processed_book:
        if token.text in punctuation or token.text in stop_words or token.text in new_signs:
            continue
        if lemmatisation:
            clean_book_tokens.append(token.lemma_)
        else:
            clean_book_tokens.append(token.text)
    return clean_book_tokens

In [ ]:
#preprocessing 1 book
preprocessed_book_1 = preprocess_book(full_text, stop_words, punctuation, lemmatisation = False)
print(preprocessed_book_1[:100])

preprocessed_book_1_lemma = preprocess_book(full_text, stop_words, punctuation, lemmatisation = True)
print(preprocessed_book_1_lemma[:100])

['I', 'believe', 'well', 'known', 'anecdote', 'exists', 'effect', 'young', 'writer', 'determined', 'make', 'commencement', 'story', 'forcible', 'original', 'enough', 'catch', 'rivet', 'attention', 'blasé', 'editors', 'penned', 'following', 'sentence', 'Hell', 'said', 'Duchess', 'Strangely', 'enough', 'tale', 'mine', 'opens', 'much', 'fashion', 'Only', 'lady', 'gave', 'utterance', 'exclamation', 'Duchess', 'It', 'day', 'early', 'June', 'I', 'transacting', 'business', 'Paris', 'returning', 'morning', 'service', 'London', 'I', 'still', 'sharing', 'rooms', 'old', 'friend', 'Belgian', 'ex', 'detective', 'Hercule', 'Poirot', 'The', 'Calais', 'express', 'singularly', 'empty', 'fact', 'compartment', 'held', 'one', 'traveller', 'I', 'made', 'somewhat', 'hurried', 'departure', 'hotel', 'busy', 'assuring', 'I', 'duly', 'collected', 'traps', 'train', 'started', 'Up', 'till', 'I', 'hardly', 'noticed', 'companion', 'I', 'violently', 'recalled', 'fact', 'existence', 'Jumping', 'seat']
['I', 'believe', 'well', 'know', 'anecdote', 'exist', 'effect', 'young', 'writer', 'determine', 'make', 'commencement', 'story', 'forcible', 'original', 'enough', 'catch', 'rivet', 'attention', 'blasé', 'editor', 'pen', 'following', 'sentence', 'hell', 'say', 'Duchess', 'strangely', 'enough', 'tale', 'mine', 'open', 'much', 'fashion', 'only', 'lady', 'give', 'utterance', 'exclamation', 'Duchess', 'it', 'day', 'early', 'June', 'I', 'transact', 'business', 'Paris', 'return', 'morning', 'service', 'London', 'I', 'still', 'share', 'room', 'old', 'friend', 'belgian', 'ex', 'detective', 'Hercule', 'Poirot', 'the', 'Calais', 'express', 'singularly', 'empty', 'fact', 'compartment', 'hold', 'one', 'traveller', 'I', 'make', 'somewhat', 'hurried', 'departure', 'hotel', 'busy', 'assure', 'I', 'duly', 'collect', 'trap', 'train', 'start', 'up', 'till', 'I', 'hardly', 'notice', 'companion', 'I', 'violently', 'recall', 'fact', 'existence', 'jump', 'seat']

For saving computational resources, I won't to this momemt process all books, but I will, may be, do in the future for indexing.

In [ ]:
#preprocessing all books
books = almost_final_df['book_title'].unique() #put all titles together as future key in a dict
print(type(books))
book_texts = {}

for book in books:
    paragraphs = almost_final_df[almost_final_df['book_title'] == book]['paragraph_text'].astype(str)
    full_text = ' '.join(paragraphs.tolist())
    book_texts[book] = full_text

In [ ]:
book_texts

##Creating an Inverted Index and Storing it as a 'pickle' file

Inverted index: https://www.geeksforgeeks.org/inverted-index/

Pickle file: https://docs.python.org/3/library/pickle.html#module-pickle

In [22]:
#the code copied from the website as a reference

# Define the documents
document1 = "The quick brown fox jumped over the lazy dog."
document2 = "The lazy dog slept in the sun."

# Step 1: Tokenize the documents
# Convert each document to lowercase and split it into words
tokens1 = document1.lower().split()
tokens2 = document2.lower().split()

# Combine the tokens into a list of unique terms
terms = list(set(tokens1 + tokens2))

# Step 2: Build the inverted index
# Create an empty dictionary to store the inverted index
inverted_index = {}

# For each term, find the documents that contain it
for term in terms:
    documents = []
    if term in tokens1:
        documents.append("Document 1")
    if term in tokens2:
        documents.append("Document 2")
    inverted_index[term] = documents

# Step 3: Print the inverted index
for term, documents in inverted_index.items():
    print(term, "->", ", ".join(documents))

in -> Document 2
lazy -> Document 1, Document 2
jumped -> Document 1
quick -> Document 1
brown -> Document 1
dog. -> Document 1
dog -> Document 2
over -> Document 1
slept -> Document 2
sun. -> Document 2
the -> Document 1, Document 2
fox -> Document 1

### Inverted index with a simple splitting and lowercasing

In [43]:
# Create a list where each element is the 'paragraph_text' from each row
documents = almost_final_df['paragraph_text'].tolist()

all_tokens = [doc.lower().split() for doc in documents] #faster option

terms = set()
for tokens in all_tokens:
    terms.update(tokens)
terms = list(terms)

inverted_index = {}

for term in terms:
    document_ids = []
    for index, tokens in enumerate(all_tokens):
       if term in tokens:
          book_title = almost_final_df.iloc[index]['book_title']
          book_id = almost_final_df.iloc[index]['book_id']
          chapter_id = almost_final_df.iloc[index]['chapter_id']
          paragraph_id = almost_final_df.iloc[index]['paragraph_id']
          document_identifier = f"Book {book_id} with the title '{book_title}', Chapter {chapter_id}, Paragraph {paragraph_id}"
          document_ids.append(document_identifier)
       inverted_index[term] = list(set(document_ids))

In [45]:
i = 0
for term, document_ids in inverted_index.items():
    if i < 15:
        print(term, "->", ", ".join(document_ids))
        i += 1
    else:
        break

comedy -> Book 7 with the title 'The Big Four', Chapter 10, Paragraph 7
rainbow? -> Book 0 with the title 'The man in the Brown Suit', Chapter 19, Paragraph 1
intervention -> Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 3
reach -> Book 8 with the title 'The Murder on the Links', Chapter 2, Paragraph 4, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 1, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 6, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 5, Paragraph 1, Book 0 with the title 'The man in the Brown Suit', Chapter 17, Paragraph 5, Book 4 with the title 'The Mystery of the Blue Train', Chapter 10, Paragraph 3
tattered -> Book 0 with the title 'The man in the Brown Suit', Chapter 2, Paragraph 4
been," -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 27, Paragraph 1
shrugged. -> Book 7 with the title 'The Big Four', Chapter 5, Paragraph 7
strategic -> Book 0 with the title 'The man in the Brown Suit', Chapter 7, Paragraph 2
buried. -> Book 7 with the title 'The Big Four', Chapter 13, Paragraph 3
transforming -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 3, Paragraph 4
think, -> Book 7 with the title 'The Big Four', Chapter 7, Paragraph 1, Book 8 with the title 'The Murder on the Links', Chapter 11, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 14, Paragraph 3, Book 0 with the title 'The man in the Brown Suit', Chapter 16, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 25, Paragraph 2, Book 8 with the title 'The Murder on the Links', Chapter 5, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 17, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 3, Book 4 with the title 'The Mystery of the Blue Train', Chapter 11, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 24, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 5, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 29, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 32, Paragraph 4, Book 7 with the title 'The Big Four', Chapter 5, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 22, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 33, Paragraph 7, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 5, Book 4 with the title 'The Mystery of the Blue Train', Chapter 18, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 32, Paragraph 3, Book 10 with the title 'The Plymouth Express Affair', Chapter 4, Paragraph 2, Book 7 with the title 'The Big Four', Chapter 6, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 28, Paragraph 1, Book 0 with the title 'The man in the Brown Suit', Chapter 23, Paragraph 7, Book 0 with the title 'The man in the Brown Suit', Chapter 36, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 19, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 23, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 34, Paragraph 6, Book 8 with the title 'The Murder on the Links', Chapter 15, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 2, Paragraph 7, Book 7 with the title 'The Big Four', Chapter 3, Paragraph 5, Book 0 with the title 'The man in the Brown Suit', Chapter 10, Paragraph 7, Book 4 with the title 'The Mystery of the Blue Train', Chapter 12, Paragraph 1
rope -> Book 8 with the title 'The Murder on the Links', Chapter 5, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 31, Paragraph 6
tool -> Book 8 with the title 'The Murder on the Links', Chapter 9, Paragraph 1, Book 8 with the title 'The Murder on the Links', Chapter 4, Paragraph 7, Book 4 with the title 'The Mystery of the Blue Train', Chapter 19, Paragraph 7
porter -> Book 0 with the title 'The man in the Brown Suit', Chapter 4, Paragraph 4, Book 8 with the title 'The Murder on the Links', Chapter 24, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 23, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 5, Paragraph 6
accident, -> Book 0 with the title 'The man in the Brown Suit', Chapter 28, Paragraph 7, Book 7 with the title 'The Big Four', Chapter 3, Paragraph 2, Book 7 with the title 'The Big Four', Chapter 10, Paragraph 7, Book 7 with the title 'The Big Four', Chapter 12, Paragraph 6

In [30]:
#storing inverted index in a pickle file
import pickle

filename = "inverted_index_simple_split_lower.pkl"

#binary write mode ('wb')
with open(filename, 'wb') as f:
    #serializing the inverted index to the file
    pickle.dump(inverted_index, f)

print(f"Inverted index has been successfully saved to '{filename}'")


#binary read mode ('rb')
with open(filename, 'rb') as f:
    #deserializing the object from the file
    loaded_inverted_index = pickle.load(f)

#analyzing
print("\nInverted index loaded from the pickle file:")
print(type(loaded_inverted_index))
print("Length of term list:", len(loaded_inverted_index))
total_postings = sum(len(postings) for postings in inverted_index.values())
print("Total postings:", total_postings)

Inverted index has been successfully saved to 'inverted_index_simple_split_lower.pkl'

Inverted index loaded from the pickle file:
<class 'dict'>
Length of term list: 27818
Total postings: 163586

In [51]:
from google.colab import files

files.download('inverted_index_simple_split_lower.pkl')

This index preserves the punctuation signs and puts some of them together with the tokens, making them impossible to get retreived later as it is unlikely the that they appear in the same way query.

### Inverted index with a simple splitting and without lowercasing

In [36]:
# Create a list where each element is the 'paragraph_text' from each row
documents = almost_final_df['paragraph_text'].tolist()

all_tokens = [doc.split() for doc in documents] #faster option

terms = set()
for tokens in all_tokens:
    terms.update(tokens)
terms = list(terms)

inverted_index = {}

for term in terms:
    document_ids = []
    for index, tokens in enumerate(all_tokens):
       if term in tokens:
          book_title = almost_final_df.iloc[index]['book_title']
          book_id = almost_final_df.iloc[index]['book_id']
          chapter_id = almost_final_df.iloc[index]['chapter_id']
          paragraph_id = almost_final_df.iloc[index]['paragraph_id']
          document_identifier = f"Book {book_id} with the title '{book_title}', Chapter {chapter_id}, Paragraph {paragraph_id}"
          document_ids.append(document_identifier)
       inverted_index[term] = list(set(document_ids))

In [37]:
i = 0
for term, document_ids in inverted_index.items():
    if i < 15:
        print(term, "->", ", ".join(document_ids))
        i += 1
    else:
        break

comedy -> Book 7 with the title 'The Big Four', Chapter 10, Paragraph 7
rainbow? -> Book 0 with the title 'The man in the Brown Suit', Chapter 19, Paragraph 1
intervention -> Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 3
reach -> Book 8 with the title 'The Murder on the Links', Chapter 2, Paragraph 4, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 1, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 6, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 5, Paragraph 1, Book 0 with the title 'The man in the Brown Suit', Chapter 17, Paragraph 5, Book 4 with the title 'The Mystery of the Blue Train', Chapter 10, Paragraph 3
tattered -> Book 0 with the title 'The man in the Brown Suit', Chapter 2, Paragraph 4
been," -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 27, Paragraph 1
Yesterday, -> Book 8 with the title 'The Murder on the Links', Chapter 4, Paragraph 5
shrugged. -> Book 7 with the title 'The Big Four', Chapter 5, Paragraph 7
strategic -> Book 0 with the title 'The man in the Brown Suit', Chapter 7, Paragraph 2
buried. -> Book 7 with the title 'The Big Four', Chapter 13, Paragraph 3
transforming -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 3, Paragraph 4
think, -> Book 7 with the title 'The Big Four', Chapter 7, Paragraph 1, Book 8 with the title 'The Murder on the Links', Chapter 11, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 14, Paragraph 3, Book 0 with the title 'The man in the Brown Suit', Chapter 16, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 25, Paragraph 2, Book 8 with the title 'The Murder on the Links', Chapter 5, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 17, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 3, Book 4 with the title 'The Mystery of the Blue Train', Chapter 11, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 24, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 5, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 29, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 32, Paragraph 4, Book 7 with the title 'The Big Four', Chapter 5, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 22, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 33, Paragraph 7, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 5, Book 4 with the title 'The Mystery of the Blue Train', Chapter 18, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 32, Paragraph 3, Book 10 with the title 'The Plymouth Express Affair', Chapter 4, Paragraph 2, Book 7 with the title 'The Big Four', Chapter 6, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 28, Paragraph 1, Book 0 with the title 'The man in the Brown Suit', Chapter 23, Paragraph 7, Book 0 with the title 'The man in the Brown Suit', Chapter 36, Paragraph 4, Book 4 with the title 'The Mystery of the Blue Train', Chapter 19, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 23, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 34, Paragraph 6, Book 8 with the title 'The Murder on the Links', Chapter 15, Paragraph 6, Book 4 with the title 'The Mystery of the Blue Train', Chapter 2, Paragraph 7, Book 7 with the title 'The Big Four', Chapter 3, Paragraph 5, Book 0 with the title 'The man in the Brown Suit', Chapter 10, Paragraph 7, Book 4 with the title 'The Mystery of the Blue Train', Chapter 12, Paragraph 1
rope -> Book 8 with the title 'The Murder on the Links', Chapter 5, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 31, Paragraph 6
Castle?” -> Book 0 with the title 'The man in the Brown Suit', Chapter 8, Paragraph 7
tool -> Book 8 with the title 'The Murder on the Links', Chapter 9, Paragraph 1, Book 8 with the title 'The Murder on the Links', Chapter 4, Paragraph 7, Book 4 with the title 'The Mystery of the Blue Train', Chapter 19, Paragraph 7

In [35]:
#storing inverted index in a pickle file
import pickle

filename = "inverted_index_simple_split.pkl"

#binary write mode ('wb')
with open(filename, 'wb') as f:
    #serializing the inverted index to the file
    pickle.dump(inverted_index, f)

print(f"Inverted index has been successfully saved to '{filename}'")


#binary read mode ('rb')
with open(filename, 'rb') as f:
    #deserializing the object from the file
    loaded_inverted_index = pickle.load(f)

#analyzing
print("\nInverted index loaded from the pickle file:")
print(type(loaded_inverted_index))
print("Length of term list", len(loaded_inverted_index))
total_postings = sum(len(postings) for postings in inverted_index.values())
print("Total postings:", total_postings)

Inverted index has been successfully saved to 'inverted_index_simple_split.pkl'

Inverted index loaded from the pickle file:
<class 'dict'>
Length of term list 29138
Total postings: 169117

In [52]:
files.download('inverted_index_simple_split.pkl')

This index has a bigger term list and the number of posting as the previous oneas it additionally stores also capitalised words together with punctuation signs.

### Inverted index with my preprocessing function

In [46]:
# Create a list where each element is the 'paragraph_text' from each row
documents = almost_final_df['paragraph_text'].tolist()

all_tokens = [preprocess_book(doc, stop_words, punctuation, lemmatisation = False) for doc in documents] #without lemmatisation

terms = set()
for tokens in all_tokens:
    terms.update(tokens)
terms = list(terms)

inverted_index = {}

for term in terms:
    document_ids = []
    for index, tokens in enumerate(all_tokens):
       if term in tokens:
          book_title = almost_final_df.iloc[index]['book_title']
          book_id = almost_final_df.iloc[index]['book_id']
          chapter_id = almost_final_df.iloc[index]['chapter_id']
          paragraph_id = almost_final_df.iloc[index]['paragraph_id']
          document_identifier = f"Book {book_id} with the title '{book_title}', Chapter {chapter_id}, Paragraph {paragraph_id}"
          document_ids.append(document_identifier)
       inverted_index[term] = list(set(document_ids))

In [47]:
i = 0
for term, document_ids in inverted_index.items():
    if i < 15:
        print(term, "->", ", ".join(document_ids))
        i += 1
    else:
        break

comedy -> Book 0 with the title 'The man in the Brown Suit', Chapter 30, Paragraph 1, Book 7 with the title 'The Big Four', Chapter 10, Paragraph 7, Book 1 with the title 'The Hunter's Lodge Case', Chapter 6, Paragraph 7
latched -> Book 0 with the title 'The man in the Brown Suit', Chapter 21, Paragraph 4
testamentary -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 7, Paragraph 1
disembarking -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 10, Paragraph 3, Book 8 with the title 'The Murder on the Links', Chapter 2, Paragraph 6
artistic -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 12, Paragraph 4, Book 0 with the title 'The man in the Brown Suit', Chapter 12, Paragraph 3, Book 7 with the title 'The Big Four', Chapter 4, Paragraph 2, Book 1 with the title 'The Hunter's Lodge Case', Chapter 5, Paragraph 4
intervention -> Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 3
reach -> Book 8 with the title 'The Murder on the Links', Chapter 2, Paragraph 4, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 1, Book 8 with the title 'The Murder on the Links', Chapter 13, Paragraph 5, Book 7 with the title 'The Big Four', Chapter 2, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 6, Paragraph 2, Book 0 with the title 'The man in the Brown Suit', Chapter 5, Paragraph 1, Book 0 with the title 'The man in the Brown Suit', Chapter 17, Paragraph 5, Book 4 with the title 'The Mystery of the Blue Train', Chapter 10, Paragraph 3
wheelbarrow -> Book 8 with the title 'The Murder on the Links', Chapter 7, Paragraph 2
tattered -> Book 0 with the title 'The man in the Brown Suit', Chapter 2, Paragraph 4
conscientious -> Book 0 with the title 'The man in the Brown Suit', Chapter 16, Paragraph 2, Book 4 with the title 'The Mystery of the Blue Train', Chapter 7, Paragraph 3, Book 0 with the title 'The man in the Brown Suit', Chapter 34, Paragraph 5
Chinamen -> Book 7 with the title 'The Big Four', Chapter 9, Paragraph 1
awoke -> Book 8 with the title 'The Murder on the Links', Chapter 16, Paragraph 7, Book 8 with the title 'The Murder on the Links', Chapter 23, Paragraph 1, Book 4 with the title 'The Mystery of the Blue Train', Chapter 5, Paragraph 6, Book 7 with the title 'The Big Four', Chapter 8, Paragraph 5, Book 0 with the title 'The man in the Brown Suit', Chapter 21, Paragraph 3, Book 0 with the title 'The man in the Brown Suit', Chapter 26, Paragraph 5, Book 8 with the title 'The Murder on the Links', Chapter 27, Paragraph 1
strategic -> Book 0 with the title 'The man in the Brown Suit', Chapter 7, Paragraph 2
transforming -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 3, Paragraph 4
killer -> Book 4 with the title 'The Mystery of the Blue Train', Chapter 35, Paragraph 5

In [48]:
#storing inverted index in a pickle file
import pickle

filename = "inverted_index_preprocess_function.pkl"

#binary write mode ('wb')
with open(filename, 'wb') as f:
    #serializing the inverted index to the file
    pickle.dump(inverted_index, f)

print(f"Inverted index has been successfully saved to '{filename}'")


#binary read mode ('rb')
with open(filename, 'rb') as f:
    #deserializing the object from the file
    loaded_inverted_index = pickle.load(f)

#analyzing
print("\nInverted index loaded from the pickle file:")
print(type(loaded_inverted_index))
print("Length of term list", len(loaded_inverted_index))
total_postings = sum(len(postings) for postings in inverted_index.values())
print("Total postings:", total_postings)

Inverted index has been successfully saved to 'inverted_index_preprocess_function.pkl'

Inverted index loaded from the pickle file:
<class 'dict'>
Length of term list 13642
Total postings: 114066

In [53]:
files.download('inverted_index_preprocess_function.pkl')

This index has the lowest number of terms and posting as it does not store stopwords and punctuation sighns, therefore it should be so far the best option for information retrieval.

For the ake of computatioal time, I will later do also the inde with the preprocessing function and lemmatisation, which should have even fewer terms and postings.

### Inverted index with mu function with lemmatisation

In [ ]:
# Create a list where each element is the 'paragraph_text' from each row
documents = almost_final_df['paragraph_text'].tolist()

all_tokens = [preprocess_book(doc, stop_words, punctuation, lemmatisation = True) for doc in documents] #with lemmatisation

terms = set()
for tokens in all_tokens:
    terms.update(tokens)
terms = list(terms)

inverted_index = {}

for term in terms:
    document_ids = []
    for index, tokens in enumerate(all_tokens):
       if term in tokens:
          book_title = almost_final_df.iloc[index]['book_title']
          book_id = almost_final_df.iloc[index]['book_id']
          chapter_id = almost_final_df.iloc[index]['chapter_id']
          paragraph_id = almost_final_df.iloc[index]['paragraph_id']
          document_identifier = f"Book {book_id} with the title '{book_title}', Chapter {chapter_id}, Paragraph {paragraph_id}"
          document_ids.append(document_identifier)
       inverted_index[term] = list(set(document_ids))

In [ ]:
i = 0
for term, document_ids in inverted_index.items():
    if i < 15:
        print(term, "->", ", ".join(document_ids))
        i += 1
    else:
        break

In [ ]:
#storing inverted index in a pickle file
import pickle

filename = "inverted_index_preprocess_function_lemma.pkl"

#binary write mode ('wb')
with open(filename, 'wb') as f:
    #serializing the inverted index to the file
    pickle.dump(inverted_index, f)

print(f"Inverted index has been successfully saved to '{filename}'")


#binary read mode ('rb')
with open(filename, 'rb') as f:
    #deserializing the object from the file
    loaded_inverted_index = pickle.load(f)

#analyzing
print("\nInverted index loaded from the pickle file:")
print(type(loaded_inverted_index))
print("Length of term list", len(loaded_inverted_index))
total_postings = sum(len(postings) for postings in inverted_index.values())
print("Total postings:", total_postings)

In [ ]:
files.download('inverted_index_preprocess_function_lemma.pkl')

##Creating a database in SQLite

SQLite: https://docs.python.org/3/library/sqlite3.html

In [57]:
import sqlite3

#create a new database and open a database connection to allow sqlite3 to work with it.
#Call sqlite3.connect() to create a connection to the database 'name' in the current working directory, implicitly creating it if it does not exist:
conn = sqlite3.connect("Agatha_Christie_books.db")

#in order to execute SQL statements and fetch results from SQL queries, we will need to use a database cursor.
cur = conn.cursor()

# writing the DataFrame to the SQLite table
#    - 'my_table' is the name of the table you want to create in the database.
#    - 'conn' is the database connection object.
#    - 'if_exists' specifies how to handle the table if it already exists:
#      - 'fail': Raise a ValueError.
#      - 'replace': Drop the table before inserting new values.
#      - 'append': Add new values to the existing table.
#    - 'index' determines whether to write the DataFrame index as a column in the table (True/False).
almost_final_df.to_sql("Agatha_Christie_books", conn, if_exists="replace", index=False)

994

In [59]:
df_preview = pd.read_sql("SELECT * FROM Agatha_Christie_books LIMIT 5;", conn)
print(df_preview)

   book_id                 book_title  chapter_id chapter_title  paragraph_id  \
0        0  The man in the Brown Suit           1      PROLOGUE             1
1        0  The man in the Brown Suit           1      PROLOGUE             2
2        0  The man in the Brown Suit           1      PROLOGUE             3
3        0  The man in the Brown Suit           1      PROLOGUE             4
4        0  The man in the Brown Suit           1      PROLOGUE             5

                                      paragraph_text
0  Nadina, the Russian dancer who had taken Paris...
1  eyes. “I will see him. The maize _peignoir,_ J...
2  it was. The suspicions aroused during the War ...
3  been a generous paymaster. I attribute much of...
4  do you think that I go?” “Hardly for pleasure ...

In [62]:
#selecting book titles
res = cur.execute("SELECT book_title FROM Agatha_Christie_books")
res.fetchone()

('The man in the Brown Suit',)

In [64]:
#selecting chapters from one book
res = cur.execute("SELECT chapter_title FROM Agatha_Christie_books WHERE book_title = 'The man in the Brown Suit'")
res.fetchall()

[('PROLOGUE',),
 ('PROLOGUE',),
 ('PROLOGUE',),
 ('PROLOGUE',),
 ('PROLOGUE',),
 ('PROLOGUE',),
 ('PROLOGUE',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER I',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER II',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER III',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER IV',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER V',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VI',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER VIII',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('CHAPTER IX',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('17. How the number persisted. It was on the 17th I had sailed from',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER X',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XI',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIII',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XIV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XV',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVI',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XVIII',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XIX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XX',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXI',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIII',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXIV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXV',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVI',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXVIII',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXIX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXX',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXI',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIII',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXIV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXV',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',),
 ('CHAPTER XXXVI',)]

The further step would be creating a vector atabase using SQLite-Vec and represetining each document as a vecotri using BM25.